const API='/api/v1';
const modules=[
 ['overview','总览 / 工作流状态',['/console/bootstrap','/workflow/status','/workflow/feature-matrix']],['market','QMT / xtdata 行情状态',['/market/xtdata-live/status']],['datahub','Data Hub 行情缓存',['/datahub/status','/datahub/symbols','/datahub/cache/status','/datahub/market/latest']],['research','Research 因子研究',['/research/context','/research/factors/latest']],['candidates','候选池排名',['/research/candidates/latest']],['agent','Agent 投研',['/agents/context','/agents/report/latest']],['strategy','Strategy 策略信号',['/strategy/context','/strategy/signals/latest']],['risk','Risk Gate 风控审查',['/risk/context','/risk/decisions/latest','/risk/report/latest']],['intent','TradeIntent dry-run',['/strategy/trade-intents/latest']],['paper','Paper Trading / Shadow Replay',['/paper-trading/status','/paper-trading/orders/latest','/paper-trading/positions/latest','/paper-trading/pnl/latest']],['monitoring','Monitoring / Alerts',['/monitoring/context','/monitoring/alerts/latest','/monitoring/circuit-breaker/latest']],['approval','Human Approval 人工确认',['/approval/status','/approval/requests/latest']],['account','Account Readonly / 持仓只读',['/account-readonly/status','/account-readonly/diagnostics','/account-readonly/asset','/account-readonly/positions']],['safety','Safety / Live Disabled 安全边界',['/safety/status','/live/status']]
];
async function get(p){const r=await fetch(API+p); if(!r.ok)throw new Error(p+': '+r.status); return r.json();}
function tags(){return ['read_only=true','dry_run=true','live_disabled=true','no_order_submitted=true','requires_human_approval=true','account_masked=true','order_submit_enabled=false','order_cancel_enabled=false','real_order_submitted=false'].map(x=>`<span class="tag">${x}</span>`).join('')}
async function show(id){document.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.id===id)); const m=modules.find(x=>x[0]===id); app.innerHTML=`<div class="card"><h2>${m[1]}</h2>${tags()}<p>加载中...</p></div>`; const rows=[]; for(const ep of m[2]){try{rows.push([ep,await get(ep)])}catch(e){rows.push([ep,{ok:false,status:'DATA_MISSING',error:e.message,read_only:true,dry_run:true,live_disabled:true}])}} app.innerHTML=`<div class="card"><h2>${m[1]}</h2>${tags()}<p>统一启动命令：<code>py scripts\\run_console_api.py --host 127.0.0.1 --port 8768</code></p><p>人工确认仅展示 CLI 提示，只展示只读审批状态与 CLI 提示，控制台不提供交易执行或自动批准入口。</p></div><div class="grid">${rows.map(([ep,d])=>`<div class="card"><h3>${ep}</h3><pre>${JSON.stringify(d,null,2)}</pre></div>`).join('')}</div>`;}
nav.innerHTML=modules.map(m=>`<button data-id="${m[0]}" onclick="show('${m[0]}')">${m[1]}</button>`).join('');
get('/health').then(h=>api.textContent='API 在线：'+h.service).catch(e=>api.textContent='API 离线：'+e.message); show('overview');
