const API='http://127.0.0.1:8768/api/v1';let catalog=[],runs=[];const app=document.querySelector('#app'),alertBox=document.querySelector('#alert');
const zhStatus={PENDING:'等待中',RUNNING:'运行中',SUCCESS:'成功',FAILED:'失败',BLOCKED:'已阻断'};
function setClock(){document.querySelector('#clock').textContent=new Date().toLocaleString('zh-CN')}setInterval(setClock,1000);setClock();
async function api(path,opt={}){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),5000);try{const r=await fetch(API+path,{...opt,signal:ctl.signal,headers:{'Content-Type':'application/json'}});clearTimeout(t);let data;try{data=await r.json()}catch(e){throw new Error('JSON 解析失败')}if(!r.ok||data.ok===false)throw new Error(data.error||'后端返回错误');return data}catch(e){throw new Error(e.name==='AbortError'?'网络超时':e.message)}}
async function refresh(){try{let h=await api('/health');document.querySelector('#apiStatus').textContent='API 状态：在线';document.querySelector('#apiStatus').className='badge ok';alertBox.textContent='API 在线：可触发白名单 dry-run 任务、查看状态、日志摘要和报告摘要。';await api('/console/summary');catalog=(await api('/tasks/catalog')).tasks;runs=(await api('/tasks')).tasks}catch(e){document.querySelector('#apiStatus').textContent='API 状态：离线';document.querySelector('#apiStatus').className='badge danger';alertBox.textContent='API 离线或异常：'+e.message+'。静态页面可浏览，任务按钮需先启动本地 API。'}}
async function runTask(id,params={}){try{alertBox.textContent='任务运行中：'+id;let d=await api('/tasks/run',{method:'POST',body:JSON.stringify({task_id:id,params})});alertBox.textContent='任务成功：'+(d.task.task_name||id);await refresh();render('tasks');openDrawer(d.task)}catch(e){alertBox.textContent=e.message.includes('阻断')?'任务被安全边界阻断：'+e.message:'任务失败：'+e.message}}
function buttons(ids){return ids.map(id=>`<button class="primary" onclick="runTask('${id}')">${(catalog.find(x=>x.task_id===id)||{}).title_zh||id}</button>`).join('')}
function taskTable(){return `<table><thead><tr><th>task_id</th><th>任务</th><th>状态</th><th>开始</th><th>结束</th><th>输出</th></tr></thead><tbody>${runs.map(r=>`<tr onclick='openDrawer(${JSON.stringify(r).replaceAll("'"," ")})'><td>${r.task_id}</td><td>${r.task_name}</td><td><span class="badge ${r.status==='SUCCESS'?'ok':r.status==='BLOCKED'?'danger':'warn'}">${zhStatus[r.status]||r.status}</span></td><td>${r.started_at||''}</td><td>${r.finished_at||''}</td><td>${(r.output_artifacts||[]).join(', ')}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无任务，请从总览或各业务模块发起 dry-run。</td></tr>'}</tbody></table>`}
function cards(){return `<div class="grid"><div class="card">今日任务状态<br><b>${runs.length}</b></div><div class="card">数据质量状态<br><b>只读 OK</b></div><div class="card">最近信号数量<br><b>${runs.reduce((a,r)=>a+((r.output&&r.output.signals)||[]).length,0)}</b></div><div class="card">Agent 报告数量<br><b>${runs.filter(r=>r.category==='AGENTS').length}</b></div><div class="card">风控拦截数量<br><b>1</b></div><div class="card dangerText">实盘状态<br><b>关闭</b></div></div>`}
function render(view='dashboard'){let html=''; if(view==='dashboard')html=`<h2>总览 Dashboard</h2>${cards()}<h3>快捷操作</h3>${buttons(['daily_pipeline_dry_run','market_snapshot_readonly','etf_rotation_candidates','agent_research_brief','list_latest_reports'])}`;
else if(view==='market')html=`<h2>行情数据</h2><p>输入代码：<input id="symbol" value="510300.SH"><button onclick="market()">获取本地只读行情快照</button></p><div id="marketBox" class="card">显示数据来源、时间、OHLCV、质量状态；API 未启动时会显示中文提示。</div>`;
else if(view==='stockpool')html=`<h2>选股中心</h2>${buttons(['etf_rotation_candidates','factor_scan','research_score_etf'])}<div class="card">候选池字段：score / rank / reasons / risk_flags</div>`;
else if(view==='strategy')html=`<h2>策略任务</h2>${buttons(['daily_pipeline_dry_run','strategy_dry_run_signals','etf_rotation_candidates'])}${taskTable()}`;
else if(view==='agents')html=`<h2>Agent 投研</h2><p>只输出结构化建议，不下单；显示 confidence、reasons、risk_flags。</p>${buttons(['agent_research_brief','agent_risk_review','agent_portfolio_review'])}`;
else if(view==='aiModels')html=aiModelsHtml();
else if(view==='backtest')html=`<h2>回测分析</h2><p>指标：total_return、max_drawdown、win_rate、trade_count。</p>${buttons(['shadow_replay_backtest','backtest_report'])}`;
else if(view==='risk')html=`<h2>风控中心</h2><div class="card dangerText">实盘未启用；不提供实盘批准按钮。</div>${buttons(['risk_gate_dry_run_check','live_readiness_blockers_review'])}`;
else if(view==='reports')html=`<h2>报告中心</h2><button onclick="loadReports()">查看最新报告</button><div id="reportsBox" class="card empty">仅列出安全白名单报告摘要，不做任意文件浏览器。</div>`;
else if(view==='tasks')html=`<h2>任务中心</h2>${taskTable()}`;
else html=`<h2>系统设置 / 安全边界</h2><div class="card"><p>API 地址：${API}</p><p>当前模式：dry-run/shadow</p><p>实盘开关：禁用</p><p>安全白名单：禁止任意命令、路径、账户查询、下单、自动批准。</p><pre>静态：py -m http.server 8767 --bind 127.0.0.1
API：py scripts\\run_console_api.py --host 127.0.0.1 --port 8768 --static-dir local_console_app_stage77</pre></div>`; app.innerHTML=html}
async function market(){try{let s=document.querySelector('#symbol').value;let d=await api('/market/snapshot?symbol='+encodeURIComponent(s));document.querySelector('#marketBox').textContent=JSON.stringify(d.snapshot,null,2)}catch(e){document.querySelector('#marketBox').textContent='API 离线/失败：'+e.message}}
async function loadReports(){try{let d=await api('/reports');document.querySelector('#reportsBox').innerHTML=d.reports.map(r=>`<p><b>${r.name}</b>｜${r.type}<br>${r.summary}</p>`).join('')}catch(e){document.querySelector('#reportsBox').textContent='报告加载失败：'+e.message}}
function openDrawer(obj){document.querySelector('#drawer').classList.add('open');document.querySelector('#drawerBody').textContent=JSON.stringify(obj,null,2)}document.querySelector('#closeDrawer').onclick=()=>document.querySelector('#drawer').classList.remove('open');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>render(b.dataset.view));refresh().then(()=>render());


function aiModelsHtml(){return `<h2>AI 模型配置</h2><div class="card"><h3>Provider 配置区</h3><label>Provider 类型<select id="aiProviderType"><option value="openai_compatible">OpenAI Compatible</option><option value="openai_official">OpenAI Official</option><option value="custom_compatible">Custom Compatible</option></select></label><label>Base URL <input id="aiBaseUrl" placeholder="https://example.com/v1"></label><label>API Key <input id="aiApiKey" type="password" autocomplete="off" placeholder="仅本次会话使用，不写入浏览器持久存储"></label><label><input id="aiSessionOnly" type="checkbox" checked> 是否仅本次会话使用</label><button class="primary" onclick="discoverAiModels()">查询可用模型</button><span id="aiMaskedKey" class="badge">masked key：未填写</span></div><div class="card"><h3>模型列表区（模型多选列表）</h3><div id="aiModelList" class="empty">请先查询模型；展示 model_id、owned_by、created、状态、能力推断。</div></div><div class="card"><h3>压力测试区</h3><label><input class="aiTestSize" type="checkbox" value="1000" checked> 1000 字</label><label><input class="aiTestSize" type="checkbox" value="3000" checked> 3000 字</label><label><input class="aiTestSize" type="checkbox" value="5000" checked> 5000 字</label><button class="primary" onclick="runAiStressTest()">开始测试</button><p id="aiProgress">当前进度：未开始。提示：压力测试可能产生 API 费用，系统串行执行、禁止高并发、禁止自动循环。</p></div><div class="card"><h3>测试报告区</h3><div id="aiReport" class="empty">展示成功/失败、响应时间、输出长度、错误类型、推荐用途、综合评分。</div></div><div class="card"><h3>模型用途映射区</h3><div id="aiUsageMapping"></div><button onclick="saveAiUsageDraft()">保存模型用途映射草稿</button></div>`}
function getAiKey(){return document.querySelector('#aiApiKey')?.value||''}
function maskKey(k){return !k?'未填写':(k.length<=8?k.slice(0,1)+'***'+k.slice(-1):k.slice(0,4)+'***'+k.slice(-4))}
async function discoverAiModels(){try{let body={provider_type:document.querySelector('#aiProviderType').value,base_url:document.querySelector('#aiBaseUrl').value,api_key:getAiKey(),timeout_seconds:60};document.querySelector('#aiMaskedKey').textContent='masked key：'+maskKey(body.api_key);let d=await api('/ai/models/discover',{method:'POST',body:JSON.stringify(body)});window.aiModels=(d.result.models||[]);renderAiModelList(window.aiModels);renderAiUsageMapping(window.aiModels);alertBox.textContent='模型发现完成：'+(d.result.model_count||0)+' 个模型'}catch(e){alertBox.textContent='模型发现失败：'+e.message}}
function renderAiModelList(models){document.querySelector('#aiModelList').innerHTML=`<table><thead><tr><th>多选 checkbox</th><th>model_id</th><th>owned_by</th><th>created</th><th>状态</th><th>能力推断</th></tr></thead><tbody>${models.map(m=>`<tr><td><input type="checkbox" class="aiModelSelect" value="${m.model_id}"></td><td>${m.model_id}</td><td>${m.owned_by||''}</td><td>${m.created||''}</td><td>${m.status||'available'}</td><td>${m.supports_chat?'chat ':''}${m.supports_responses?'responses':''}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">暂无模型</td></tr>'}</tbody></table>`}
function selectedAiModels(){return Array.from(document.querySelectorAll('.aiModelSelect:checked')).map(x=>x.value)}
function selectedAiSizes(){return Array.from(document.querySelectorAll('.aiTestSize:checked')).map(x=>Number(x.value))}
async function runAiStressTest(){if(!confirm('压力测试可能产生 API 费用；每个模型每种长度只测 1 次，串行执行，是否继续？'))return;try{let body={provider_type:document.querySelector('#aiProviderType').value,base_url:document.querySelector('#aiBaseUrl').value,api_key:getAiKey(),selected_models:selectedAiModels(),test_sizes:selectedAiSizes(),timeout_seconds:90};document.querySelector('#aiProgress').textContent='当前进度：串行测试中（最多 15 个请求）';let d=await api('/ai/models/stress-test',{method:'POST',body:JSON.stringify(body)});document.querySelector('#aiProgress').textContent='当前进度：完成';let rows=(d.report.test_results||[]).map(r=>`<tr><td>${r.model_id}</td><td>${r.input_chars}</td><td>${r.success?'成功':'失败'}</td><td>${r.elapsed_ms}</td><td>${r.output_chars}</td><td>${r.error_type||''}</td><td>${r.recommendation||''}</td></tr>`).join('');document.querySelector('#aiReport').innerHTML=`<p>综合评分：${d.report.summary.score}；成功 ${d.report.summary.success}/${d.report.summary.total}</p><table><tbody>${rows}</tbody></table>`}catch(e){document.querySelector('#aiProgress').textContent='当前进度：失败';alertBox.textContent='压力测试失败：'+e.message}}
function renderAiUsageMapping(models){let roles=['技术面 Agent 模型','基本面 Agent 模型','情绪新闻 Agent 模型','多空辩论 Agent 模型','风险 Agent 模型','组合经理 Agent 模型','通用 fallback 模型'];let opts=(models||[]).map(m=>`<option value="${m.model_id}">${m.model_id}</option>`).join('');document.querySelector('#aiUsageMapping').innerHTML=roles.map((r,i)=>`<label>${r}<select class="aiUsage" data-role="role_${i}"><option value="">未选择</option>${opts}</select></label>`).join('<br>')}
async function saveAiUsageDraft(){let mappings={};document.querySelectorAll('.aiUsage').forEach(x=>mappings[x.dataset.role]=x.value);let d=await api('/ai/model-usage/draft',{method:'POST',body:JSON.stringify({mappings})});openDrawer(d.draft)}
