const SAFETY=['read_only=true','dry_run=true','not_live_trading=true','no_xttrader=true','no_order_submitted=true','no_account_query=true'];
const FLOW_APIS=['/api/v1/market/xtdata-live/status','/api/v1/datahub/status','POST factor_research_dry_run','POST agent_research_dry_run','POST factor_strategy_dry_run','POST risk_gate_dry_run','/api/v1/approval/status','/api/v1/paper-trading/status'];
const MODULES=[
 {id:'overview',name:'总览',status:'INTERACTIVE',apis:['/api/v1/health','/api/v1/console/summary','/api/v1/tasks/catalog'],source:'console api runtime',task:null,kind:'generic'},
 {id:'workflow',name:'系统运行工作台',status:'INTERACTIVE',apis:['/api/v1/workflow/status','/api/v1/workflow/reports'],source:'local_console_workflow_stage87/*.json; artifacts/reports/stage87/workflow/*.json',task:'workflow_dry_run_check',kind:'workflow'},
 {id:'featureMatrix',name:'功能矩阵',status:'INTERACTIVE',apis:['/api/v1/workflow/feature-matrix'],source:'Workflow Console backend feature matrix',task:null,kind:'featureMatrix'},
 {id:'marketdata',name:'行情数据',status:'INTERACTIVE',apis:['/api/v1/market/snapshot','/api/v1/market/sandbox/symbols'],source:'local readonly/mock + local_console_market_stage84',task:'market_snapshot_readonly',kind:'generic'},
 {id:'factor',name:'因子研究',status:'INTERACTIVE',apis:['/api/v1/factor/context','/api/v1/factor/candidates/latest','/api/v1/factor/report/latest','/api/v1/factors/catalog','/api/v1/factors/config'],source:'local_console_factor_stage79/*.json; task-store fallback',task:'factor_research_dry_run',fallbackTask:'factor_scan',kind:'factor'},
 {id:'selection',name:'选股中心',status:'INTERACTIVE',apis:['/api/v1/strategy/signals/latest','/api/v1/strategy/trade-intents/latest','/api/v1/risk/decisions/latest','/api/v1/strategy/report'],source:'factor strategy dry-run task output',task:'factor_strategy_dry_run',kind:'generic'},
 {id:'strategy',name:'策略任务',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks','/api/v1/strategy/context'],source:'console task registry/store + strategy context',task:'daily_pipeline_dry_run',kind:'generic'},
 {id:'agents',name:'Agent 投研',status:'INTERACTIVE',apis:['/api/v1/agents/context','/api/v1/agents/model-usage','/api/v1/agents/runs/latest','/api/v1/agents/debate/latest','/api/v1/agents/risk-review/latest','/api/v1/agents/portfolio-review/latest','/api/v1/agents/report/latest'],source:'local_console_agent_stage81/*.json',task:'agent_research_dry_run',kind:'generic'},
 {id:'ai',name:'AI 模型配置',status:'INTERACTIVE',apis:['/api/v1/ai/models/latest','/api/v1/ai/benchmark/latest','/api/v1/ai/model-usage/draft'],source:'AI provider discovery/stress-test draft cache',task:'ai_model_discovery',kind:'generic'},
 {id:'backtest',name:'回测分析',status:'INTERACTIVE',apis:['/api/v1/backtest/report/latest','/api/v1/backtest/performance/latest','/api/v1/backtest/attribution/latest','/api/v1/backtest/agent-comparison/latest','/api/v1/backtest/shadow-replay/latest'],source:'local_console_backtest_stage82/*.json',task:'backtest_dashboard_dry_run',kind:'backtest'},
 {id:'risk',name:'风控中心',status:'INTERACTIVE',apis:['/api/v1/risk/context','/api/v1/risk/decisions/latest','/api/v1/risk/report/latest','/api/v1/monitoring/alerts/latest'],source:'Risk Gate dry-run + monitoring reports',task:'risk_gate_dry_run',kind:'monitoring'},
 {id:'reports',name:'报告中心',status:'INTERACTIVE',apis:['/api/v1/reports','/api/v1/workflow/reports','/api/v1/backtest/report/latest','/api/v1/monitoring/report/latest'],source:'whitelisted report summaries + stage reports',task:'generate_daily_report',kind:'generic'},
 {id:'tasks',name:'任务中心',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks'],source:'console task registry/store',task:'list_latest_reports',kind:'generic'},
 {id:'settings',name:'系统设置',status:'BACKEND_MISSING',apis:['/api/v1/live/status'],expected:'/api/v1/settings',source:'settings API not implemented; live status is safety API',need:'实现只读设置查询、运行环境检查和配置审计 API',kind:'placeholder'},
 {id:'marketReplay',name:'行情回放',status:'INTERACTIVE',apis:['/api/v1/market/sandbox/report/latest','/api/v1/market/sandbox/snapshots','/api/v1/market/sandbox/bars','/api/v1/market/sandbox/replay/latest','/api/v1/market/sandbox/quality/latest'],source:'local_console_market_stage84/*.json',task:'market_replay_sandbox',kind:'market'},
 {id:'xtBoundary',name:'xtdata 边界/启用',status:'INTERACTIVE',apis:['/api/v1/xtdata/boundary/report','/api/v1/xtdata-enable/report','/api/v1/market/xtdata/config','/api/v1/market/xtdata/import-guard'],source:'local_console_xtdata_stage85/*.json; local_console_xtdata_enable_stage86/*.json',task:'xtdata_boundary_dry_run',kind:'generic'},
 {id:'xtLive',name:'xtdata 只读行情',status:'INTERACTIVE',apis:['/api/v1/market/xtdata-live/status','/api/v1/market/xtdata-live/snapshots','/api/v1/market/xtdata-live/bars','/api/v1/market/xtdata-live/safety','/api/v1/market/xtdata-live/report'],source:'local_console_xtdata_live_stage87/*.json; sandbox fallback when unavailable',task:'xtdata_live_readonly_smoke',kind:'market'},
 {id:'artifacts',name:'artifacts 迁移',status:'INTERACTIVE',apis:['/api/v1/artifacts/migration/report','/api/v1/artifacts/registry'],source:'local_console_artifact_migration_stage87/*.json',task:'xtdata_live_readonly_smoke',kind:'generic'}
];
const app=document.getElementById('app'), menu=document.getElementById('menu'); let state={}; let xtLiveRealReadonly=false;
menu.innerHTML=MODULES.map(m=>`<a href="#${m.id}" data-id="${m.id}">${m.name}</a>`).join('');
window.addEventListener('hashchange',render); render();
function active(){return MODULES.find(m=>m.id===(location.hash||'#overview').slice(1))||MODULES[0]}
function render(){const m=active(); document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.id===m.id)); renderInteractive(m); loadModule(m);}
function tags(){return SAFETY.map(x=>`<span class="tag">${x}</span>`).join('')}
const STAGE87_COMPAT_TEXT='当前页面：仅占位 状态：后端待开发 预计后端接口 需要实现 前端功能矩阵 / Feature Matrix 模块名称 前端页面状态 后端 API 状态 数据源路径 是否可交互 是否 dry-run 是否 read-only 当前是否占位 下一步动作 INTERACTIVE STATIC_PLACEHOLDER BACKEND_MISSING API_ERROR DATA_MISSING fallback/mock_data /api/v1/xtdata-live/status';
function renderInteractive(m){if(m.id==='xtLive')return renderXtLive(); let top=m.kind==='workflow'?`<h2>QMT AI 系统运行工作台</h2><p>主链路：QMT Gateway -&gt; Data Hub -&gt; Research -&gt; TradingAgents -&gt; Strategy Engine -&gt; Risk Gate -&gt; Human Approval -&gt; Paper Trading / Shadow Trading</p><button class="primary" onclick="runWorkflowCheck()">运行系统链路检查</button>`:`<h2>${m.name}</h2>`;app.innerHTML=`${top}<p>${tags()} <span class="tag">${m.status}</span></p><p>数据来源：<span class="source">${m.source}</span></p><div class="actions"><button onclick="loadModuleById('${m.id}')">刷新</button>${m.task?`<button class="secondary" onclick="runTask('${m.id}')">运行 dry-run 任务</button>`:''}<button onclick="showReport('${m.id}')">查看报告</button></div><div id="status" class="loading">加载中...</div><div id="content"></div><details><summary>原始 JSON 折叠查看区 / 原始 JSON 折叠区</summary><pre id="raw">等待加载</pre></details>`}
window.loadModuleById=id=>loadModule(MODULES.find(m=>m.id===id));

function componentStatusCard(title,value,tone='info',note=''){return `<div class="status-card ${tone}"><p>${escapeHtml(title)}</p><strong>${escapeHtml(value)}</strong>${note?`<small>${escapeHtml(note)}</small>`:''}</div>`;}
function componentSafetyBanner(obj={}){const safe=obj.no_xttrader!==false&&obj.no_order_submitted!==false&&obj.no_account_query!==false; if(!safe)return `<div class="safety-banner risk"><b>安全边界异常，请停止使用并检查配置</b></div>`; return `<div class="safety-banner"><b>当前仅启用 xtdata 只读行情：</b><span>不会调用 xttrader</span><span>不会查询账户/资金/持仓</span><span>不会提交订单</span><span>不会撤单</span></div>`;}
function componentJsonDetails(label='高级调试：查看原始 JSON'){return `<details class="debug-json"><summary>${label}</summary><pre id="raw">等待加载</pre></details>`;}
function componentEmptyState(text='暂无数据，请先刷新或读取行情。'){return `<div class="empty-state">${escapeHtml(text)}</div>`;}
function componentBackendMissing(api){return `<div class="placeholder card"><h3>BACKEND_MISSING 占位</h3><p>后端待开发，需要新增 ${escapeHtml(api)} API。</p></div>`;}
function xtLiveQuery(extra={}){const params=new URLSearchParams(extra); if(xtLiveRealReadonly){params.set('enable_xtdata','true'); params.set('allow_import_xtdata','true'); params.set('allow_real_market_data','true'); params.set('allow_connect_miniqmt','true'); params.set('read_only','true'); params.set('allow_xttrader','false'); params.set('allow_order_submit','false'); params.set('allow_account_query','false');} return params.toString()?`?${params.toString()}`:'';}
function xtControls(){return `<section class="card control-card"><h3>行情控制区</h3><div class="form-grid"><label>标的输入框<input id="xtSymbols" value="510300.SH,510500.SH,588000.SH"></label><label>周期选择<select id="xtPeriod"><option>1m</option><option>5m</option><option>15m</option><option selected>1d</option></select></label><label>K线数量选择<select id="xtLimit"><option selected>20</option><option>60</option><option>120</option><option>250</option></select></label></div><label class="confirm"><input id="xtLiveConfirm" type="checkbox"> 人工确认：我确认只启用 xtdata 只读行情，不启用 xttrader、不查询账户、不下单</label><div class="actions"><button class="primary" onclick="enableXtLiveReadonly()">启用真实 xtdata 只读行情</button><button onclick="disableXtLiveReadonly()">关闭真实行情，回到 Sandbox</button><button onclick="loadXtLive('status')">刷新状态</button><button onclick="loadXtLive('snapshots')">获取快照</button><button onclick="loadXtLive('bars')">获取K线</button></div><p class="muted">默认 Sandbox；勾选人工确认后，本页面会话才会附加真实 xtdata 只读参数。</p></section>`}
function renderXtLive(){app.innerHTML=`<div class="page-header"><h2>xtdata 只读行情工作台</h2><p>面向交易/投研的只读行情工作台，保留底部折叠调试信息。</p></div><section><h3>顶部状态总览</h3><div id="statusOverview" class="status-grid">${xtStatusOverview({})}</div></section><section><h3>安全边界提示</h3><div id="safetyBoundary">${componentSafetyBanner({})}</div></section>${xtControls()}<div id="status" class="loading">等待加载...</div><div id="content"></div>${componentJsonDetails()}`;}
function boolText(v){return v===true?'是':v===false?'否':'待确认'}
function xtStatusOverview(obj={}){const real=obj.real_market_data===true&&obj.sandbox_fallback===false; const sandbox=obj.real_market_data===false&&obj.sandbox_fallback===true; const safe=obj.no_xttrader!==false&&obj.no_order_submitted!==false&&obj.no_account_query!==false; return componentStatusCard('行情模式',real?'真实 xtdata 行情':sandbox?'Sandbox 模拟行情':(xtLiveRealReadonly?'真实 xtdata 行情待连接':'Sandbox 模拟行情'),'success')+componentStatusCard('MiniQMT',obj.mini_qmt_connected===true?'MiniQMT 已连接':obj.mini_qmt_connected===false?'MiniQMT 未连接':'MiniQMT 待确认',obj.mini_qmt_connected?'success':'muted')+componentStatusCard('数据源',real?'真实行情':'模拟数据',real?'success':'warn')+componentStatusCard('安全状态',safe?'只读安全：未接交易接口':'风险阻断',safe?'success':'risk');}
window.enableXtLiveReadonly=()=>{const c=document.getElementById('xtLiveConfirm'); if(!c||!c.checked){document.getElementById('status').innerHTML='<div class="error">请先勾选人工确认复选框。</div>'; return;} xtLiveRealReadonly=true; document.getElementById('status').textContent='正在连接 MiniQMT...'; loadXtLive('status');};
window.disableXtLiveReadonly=()=>{xtLiveRealReadonly=false; loadXtLive('status');};
function xtInputs(kind){const symbols=(document.getElementById('xtSymbols')?.value||'510300.SH,510500.SH,588000.SH').trim(); const period=document.getElementById('xtPeriod')?.value||'1d'; const limit=document.getElementById('xtLimit')?.value||'20'; return kind==='bars'?{symbol:symbols.split(',')[0].trim(),period,limit}:{symbols};}
async function loadXtLive(kind='status'){const status=document.getElementById('status'), raw=document.getElementById('raw'), content=document.getElementById('content'); if(!status)return; const msg={status:'正在刷新状态...',snapshots:'正在读取行情...',bars:'正在刷新 K线...'}[kind]||'正在读取行情...'; status.textContent=msg; const urls={status:'/api/v1/market/xtdata-live/status',snapshots:'/api/v1/market/xtdata-live/snapshots',bars:'/api/v1/market/xtdata-live/bars'}; const url=urls[kind]+xtLiveQuery(xtInputs(kind)); try{const data=await fetchJson(url); state.xtLive={url,data,kind}; const obj=xtObj(data); document.getElementById('statusOverview').innerHTML=xtStatusOverview(obj); document.getElementById('safetyBoundary').innerHTML=componentSafetyBanner(obj); status.textContent=`已更新：${kind==='bars'?'K线数据':kind==='snapshots'?'行情快照':'连接状态'}；数据源 ${obj.real_market_data?'真实 xtdata':'Sandbox'}。`; raw.textContent=JSON.stringify(data,null,2); content.innerHTML=xtLiveView(data,kind);}catch(e){status.innerHTML=`<div class="error">连接失败：${escapeHtml(e.message)}</div>`; raw.textContent=JSON.stringify({status:'API_ERROR',error:e.message},null,2); content.innerHTML=xtDiagnostics({connection_error:e.message,sandbox_fallback:!xtLiveRealReadonly});}}
function xtObj(d){return d.status||d.snapshots||d.bars||d.report||d;}
function xtRows(obj){let rows=obj.bars||obj.snapshots||obj.data||[]; if(!Array.isArray(rows)&&rows&&typeof rows==='object')rows=Object.entries(rows).flatMap(([symbol,v])=>(Array.isArray(v)?v:[v]).map(x=>({...x,symbol:x.symbol||symbol}))); return Array.isArray(rows)?rows:[];}
function fmtNum(n,d=3){n=Number(n); return Number.isFinite(n)?n.toFixed(d):'--'}
function fmtPct(n){n=Number(n); return Number.isFinite(n)?`${n>=0?'+':''}${(n*100).toFixed(2)}%`:'--'}
function fmtBig(n){n=Number(n); if(!Number.isFinite(n))return '--'; if(Math.abs(n)>=1e8)return (n/1e8).toFixed(2)+'亿'; if(Math.abs(n)>=1e4)return (n/1e4).toFixed(2)+'万'; return String(Math.round(n));}
function rowTime(r){return r.date||r.datetime||r.time||r.timestamp||r.index||'--'}
function summaries(rows,obj){const by={}; rows.forEach(r=>{const s=r.symbol||obj.symbol||document.getElementById('xtSymbols')?.value?.split(',')[0]||'510300.SH'; (by[s]||(by[s]=[])).push(r)}); if(!Object.keys(by).length)return componentEmptyState('暂无摘要数据，请点击获取快照或获取K线。'); return `<div class="summary-grid">${Object.entries(by).map(([s,rs])=>{rs=[...rs].sort((a,b)=>String(rowTime(b)).localeCompare(String(rowTime(a)))); const last=rs[0]||{}, prev=rs[1]||{}; const price=last.lastPrice??last.price??last.close; const prevClose=last.preClose??last.prev_close??prev.close; const ch=Number(price)-Number(prevClose); const pct=Number(prevClose)?ch/Number(prevClose):last.pct_chg; return `<div class="summary-card"><h3>${escapeHtml(s)}</h3><p>最新价 / 收盘价 <b>${fmtNum(price)}</b></p><p>涨跌额 <b class="${ch>=0?'up':'down'}">${Number.isFinite(ch)?(ch>=0?'+':'')+ch.toFixed(3):'--'}</b></p><p>涨跌幅 <b class="${pct>=0?'up':'down'}">${fmtPct(pct)}</b></p><p>成交量 ${fmtBig(last.volume)}</p><p>成交额 ${fmtBig(last.amount)}</p><p>最近行情时间 ${escapeHtml(rowTime(last))}</p><p>数据源：${obj.real_market_data?'真实 xtdata':'Sandbox'}</p></div>`}).join('')}</div>`;}
function xtKTable(rows,obj){if(!rows.length)return componentEmptyState('暂无 K 线数据，请点击获取K线。'); const symbol=rows[0].symbol||obj.symbol||'510300.SH', period=document.getElementById('xtPeriod')?.value||'1d', limit=document.getElementById('xtLimit')?.value||'20'; const sorted=[...rows].sort((a,b)=>String(rowTime(b)).localeCompare(String(rowTime(a)))).slice(0,20); const tabs=[...(document.getElementById('xtSymbols')?.value||'510300.SH,510500.SH,588000.SH').split(',')].map(x=>x.trim()).filter(Boolean); return `<div class="card"><div class="table-title"><h3>${escapeHtml(symbol)} 最近 20 根 ${escapeHtml(period)} K线</h3><div class="tabs">${tabs.map((t,i)=>`<button class="tab ${i===0?'active':''}">${escapeHtml(t)}</button>`).join('')}</div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>时间戳</th><th>开盘</th><th>最高</th><th>最低</th><th>收盘</th><th>涨跌幅</th><th>成交量</th><th>成交额</th><th>数据源</th></tr></thead><tbody>${sorted.map((r,i)=>{const prev=sorted[i+1]||{}; const pct=Number(prev.close)?(Number(r.close)-Number(prev.close))/Number(prev.close):Number(r.pct_chg); return `<tr><td>${escapeHtml(rowTime(r))}</td><td>${escapeHtml(r.timestamp||r.time||'--')}</td><td>${fmtNum(r.open)}</td><td>${fmtNum(r.high)}</td><td>${fmtNum(r.low)}</td><td>${fmtNum(r.close)}</td><td class="${pct>=0?'up':'down'}">${fmtPct(pct)}</td><td>${fmtBig(r.volume)}</td><td>${fmtBig(r.amount)}</td><td>${obj.real_market_data?'真实 xtdata':'Sandbox'}</td></tr>`}).join('')}</tbody></table></div></div>`;}
function xtDiagnostics(obj){const errs=[['连接失败',obj.connection_error],['导入失败',obj.import_error],['快照读取失败',obj.get_full_tick_error],['K线读取失败',obj.get_market_data_ex_error||obj.error_message]].filter(x=>x[1]); if(!errs.length)return `<div class="card"><h3>诊断信息</h3><p class="ok">当前无错误，真实 xtdata 只读行情正常。</p><p>已自动回退到 Sandbox：${obj.sandbox_fallback?'是':'否'}</p></div>`; return `<div class="card"><h3>诊断信息</h3>${errs.map(([k,v])=>`<p><b>${k}：</b>${escapeHtml(v)}</p>`).join('')}<p>已自动回退到 Sandbox：${obj.sandbox_fallback?'是':'否'}</p></div>`;}
function xtLiveView(d,kind){const obj=xtObj(d), rows=xtRows(obj); return `<section><h3>行情摘要卡片</h3>${summaries(rows,obj)}</section><section><h3>K 线数据表</h3>${xtKTable(rows,obj)}</section>${xtDiagnostics(obj)}`;}

async function fetchJson(url){const r=await fetch(url); if(r.status===404)return {ok:false,status:'BACKEND_MISSING',next_action:`后端待开发，需要新增 ${url} API`,read_only:true,dry_run:true,no_order_submitted:true}; const j=await r.json(); if(!r.ok||j.ok===false) throw new Error(url+': '+(j.error||r.status)); return j;}
async function loadModule(m){if(m&&m.id==='xtLive')return loadXtLive('status'); if(!m||!m.apis.length)return; const status=document.getElementById('status'), raw=document.getElementById('raw'), content=document.getElementById('content'); status.textContent='加载中...'; content.innerHTML=''; try{const entries=await Promise.all(m.apis.map(async url=>[url,await fetchJson(url)])); const data=Object.fromEntries(entries); state[m.id]=data; status.textContent='已加载 '+entries.length+' 个相对路径 API；Network 可见 '+m.apis.join(', '); raw.textContent=JSON.stringify(data,null,2); content.innerHTML=view(m,data);}catch(e){status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`; raw.textContent=JSON.stringify({status:'API_ERROR',error:e.message},null,2);}}
async function postTask(task_id){let r=await fetch('/api/v1/tasks/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id,params:{limit:5,read_only:true,dry_run:true,no_order_submitted:true}})}); let j=await r.json(); if(!r.ok||j.ok===false) throw new Error(j.error||r.status); return j;}
async function runTask(id){const m=MODULES.find(x=>x.id===id); const status=document.getElementById('status'); status.textContent='dry-run 任务运行中...'; try{await postTask(m.task); await loadModule(m);}catch(e){if(m.fallbackTask){try{await postTask(m.fallbackTask); await loadModule(m); return;}catch(e2){e=e2}} status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`;}}
async function runWorkflowCheck(){const status=document.getElementById('status'); status.textContent='系统链路 dry-run 顺序检查中...'; const out=[]; for(const step of FLOW_APIS){try{if(step.startsWith('POST ')){out.push([step,await postTask(step.replace('POST ',''))]);}else{out.push([step,await fetchJson(step)]);}}catch(e){out.push([step,{status:'BACKEND_MISSING',error:e.message,next_action:`后端待开发，需要新增 ${step} API`}]);}} await postTask('workflow_dry_run_check'); state.workflowRun=Object.fromEntries(out); document.getElementById('raw').textContent=JSON.stringify(state.workflowRun,null,2); document.getElementById('content').innerHTML=workflowRunTable(state.workflowRun); status.textContent='系统链路检查完成：dry-run only，未下单。';}
function showReport(id){const raw=document.getElementById('raw'); raw.scrollIntoView({behavior:'smooth'});}
function view(m,d){if(m.kind==='workflow')return workflowView(d); if(m.kind==='featureMatrix')return featureMatrixView(d); if(m.kind==='factor')return factorView(d); return cards('接口数据 / 安全状态 / 下一步建议',d)}
function workflowView(d){const wf=d['/api/v1/workflow/status']?.workflow||[]; return `<div class="grid">${wf.map(x=>`<div class="card"><h3>${x.module||x.layer}</h3><p><b>当前状态</b> <span class="tag">${x.status}</span></p><p><b>后端 API 状态</b> ${x.api_status}</p><p><b>数据源路径</b> <span class="source">${x.data_source_path||x.data_source}</span></p><p><b>最近运行时间</b> ${x.last_run_time||'DATA_MISSING'}</p><p><b>是否可交互</b> ${x.interactive?'是':'否'}；<b>是否后端待开发</b> ${x.backend_missing?'是 BACKEND_MISSING':'否'}</p><p><b>安全边界</b> ${x.safety_boundary}</p><button onclick="runTask('${active().id}')">运行按钮</button> <button onclick="loadModuleById('${active().id}')">刷新按钮</button> <button onclick="showReport('${active().id}')">查看报告按钮</button><p><b>下一步建议</b> ${x.next_action}</p></div>`).join('')}</div>`}
function workflowRunTable(obj){return `<h3>一键顺序检查结果</h3><table><thead><tr><th>步骤</th><th>状态</th><th>下一步建议</th></tr></thead><tbody>${Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${v.status||v.task?.status||'READY'}</td><td>${v.next_action||v.task?.message||'继续下一层 dry-run'}</td></tr>`).join('')}</tbody></table>`}
function featureMatrixView(d){const rows=d['/api/v1/workflow/feature-matrix']?.features||[]; return `<table class="matrix"><thead><tr><th>功能</th><th>状态</th><th>API</th><th>说明</th><th>read_only</th><th>no_order_submitted</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.feature}</td><td><span class="tag ${r.status.includes('DISABLED')?'warn':''}">${r.status}</span></td><td>${r.api||'BACKEND_MISSING'}</td><td>${r.note}</td><td>${r.read_only}</td><td>${r.no_order_submitted}</td></tr>`).join('')}</tbody></table>`}
function cards(title,d){return `<div class="grid"><div class="card"><h3>${title}</h3>${tableFromData(d)}</div><div class="card"><h3>安全状态</h3>${tags()}<p class="muted">BACKEND_MISSING / DISABLED_FOR_SAFETY 会在原始 JSON 中明确显示。</p></div></div>`}
function factorView(d){const c=(d['/api/v1/factor/candidates/latest']?.candidates||d['/api/v1/factors/candidates']?.candidates||[]);return `<div class="card"><h3>factor values / composite_score / risk_flags / ranking</h3>${candidateTable(c)}</div><div class="grid"><div class="card"><h3>因子配置面板</h3>${tableFromData(d['/api/v1/factors/config']||{})}</div><div class="card"><h3>因子报告</h3>${tableFromData(d['/api/v1/factor/report/latest']||{})}</div></div>`}
function candidateTable(rows){if(!Array.isArray(rows)||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING，暂无候选池；可点击 dry-run 生成或查看原始 JSON。</p>';const sorted=[...rows].sort((a,b)=>(b.composite_score||b.score||0)-(a.composite_score||a.score||0));return `<table><thead><tr><th>ranking</th><th>symbol/factor</th><th>factor values</th><th>composite_score</th><th>risk_flags</th><th>fallback/mock_data</th></tr></thead><tbody>${sorted.map((r,i)=>`<tr><td>${i+1}</td><td>${r.symbol||r.factor_id||r.name||''}</td><td><pre>${escapeHtml(JSON.stringify(r.factor_values||r.values||r,null,2))}</pre></td><td>${r.composite_score??r.score??''}</td><td class="risk">${(r.risk_flags||[]).join(', ')}</td><td>${r.fallback_used||r.mock_data?'是':'否'}</td></tr>`).join('')}</tbody></table>`}
function tableFromData(data){const obj=unwrap(data); if(Array.isArray(obj))return arrTable(obj); if(obj&&typeof obj==='object')return arrTable(Object.entries(obj).map(([key,value])=>({key,value:typeof value==='object'?JSON.stringify(value):value}))); return `<pre>${escapeHtml(JSON.stringify(data,null,2))}</pre>`}
function unwrap(x){if(!x||typeof x!=='object')return x; for(const k of ['features','workflow','alerts','snapshots','bars','symbols','tasks','reports','performance','attribution','agent_comparison','report','status','registry','decisions','signals','trade_intents']) if(x[k]!==undefined) return x[k]; return x}
function arrTable(rows){if(!rows||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING 或当前输出为空。</p>'; const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))].slice(0,8); return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${escapeHtml(typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??''))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
