const SAFETY=['read_only=true','dry_run=true','not_live_trading=true','no_xttrader=true','no_order_submitted=true','no_account_query=true'];
const FLOW_APIS=['/api/v1/market/xtdata-live/status','/api/v1/datahub/status','POST factor_research_dry_run','POST agent_research_dry_run','POST factor_strategy_dry_run','POST risk_gate_dry_run','/api/v1/approval/status','/api/v1/paper-trading/status'];
const MODULES=[
 {id:'overview',name:'总览',status:'INTERACTIVE',apis:['/api/v1/health','/api/v1/console/summary','/api/v1/tasks/catalog'],source:'console api runtime',task:null,kind:'generic'},
 {id:'workflow',name:'系统运行工作台',status:'INTERACTIVE',apis:['/api/v1/workflow/status','/api/v1/workflow/reports'],source:'local_console_workflow_stage87/*.json; artifacts/reports/stage87/workflow/*.json',task:'workflow_dry_run_check',kind:'workflow'},
 {id:'featureMatrix',name:'功能矩阵',status:'INTERACTIVE',apis:['/api/v1/workflow/feature-matrix'],source:'Workflow Console backend feature matrix',task:null,kind:'featureMatrix'},
 {id:'marketdata',name:'行情数据',status:'INTERACTIVE',apis:['/api/v1/market/snapshot','/api/v1/market/sandbox/symbols'],source:'local readonly/mock + local_console_market_stage84',task:'market_snapshot_readonly',kind:'generic'},
 {id:'factor',name:'因子研究',status:'INTERACTIVE',apis:['/api/v1/factor/context','/api/v1/factor/candidates/latest','/api/v1/factor/report/latest','/api/v1/factors/catalog','/api/v1/factors/config'],source:'local_console_factor_stage79/*.json; task-store fallback',task:'factor_research_dry_run',fallbackTask:'factor_scan',kind:'factor'},
 {id:'selection',name:'选股中心',status:'INTERACTIVE',apis:['/api/v1/strategy/signals/latest','/api/v1/strategy/trade-intents/latest','/api/v1/risk/decisions/latest','/api/v1/strategy/report'],source:'factor strategy dry-run task output',task:'factor_strategy_dry_run',kind:'generic'},
 {id:'strategy',name:'策略任务',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks','/api/v1/strategy/context'],source:'console task registry/store + strategy context',task:'daily_pipeline_dry_run',kind:'generic'},
 {id:'agents',name:'Agent 投研',status:'INTERACTIVE',apis:['/api/v1/agents/context','/api/v1/agents/model-usage','/api/v1/agents/runs/latest','/api/v1/agents/debate/latest','/api/v1/agents/risk-review/latest','/api/v1/agents/portfolio-review/latest','/api/v1/agents/report/latest'],source:'local_console_agent_stage81/*.json',task:'agent_research_dry_run',kind:'generic'},
 {id:'ai',name:'AI 模型配置',status:'INTERACTIVE',apis:['/api/v1/ai/models/latest','/api/v1/ai/benchmark/latest','/api/v1/ai/model-usage/draft'],source:'AI provider discovery/stress-test draft cache',task:'ai_model_discovery',kind:'generic'},
 {id:'backtest',name:'回测分析',status:'INTERACTIVE',apis:['/api/v1/backtest/report/latest','/api/v1/backtest/performance/latest','/api/v1/backtest/attribution/latest','/api/v1/backtest/agent-comparison/latest','/api/v1/backtest/shadow-replay/latest'],source:'local_console_backtest_stage82/*.json',task:'backtest_dashboard_dry_run',kind:'backtest'},
 {id:'risk',name:'风控中心',status:'INTERACTIVE',apis:['/api/v1/risk/context','/api/v1/risk/decisions/latest','/api/v1/risk/report/latest','/api/v1/monitoring/alerts/latest'],source:'Risk Gate dry-run + monitoring reports',task:'risk_gate_dry_run',kind:'monitoring'},
 {id:'reports',name:'报告中心',status:'INTERACTIVE',apis:['/api/v1/reports','/api/v1/workflow/reports','/api/v1/backtest/report/latest','/api/v1/monitoring/report/latest'],source:'whitelisted report summaries + stage reports',task:'generate_daily_report',kind:'generic'},
 {id:'tasks',name:'任务中心',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks'],source:'console task registry/store',task:'list_latest_reports',kind:'generic'},
 {id:'settings',name:'系统设置',status:'BACKEND_MISSING',apis:['/api/v1/live/status'],expected:'/api/v1/settings',source:'settings API not implemented; live status is safety API',need:'实现只读设置查询、运行环境检查和配置审计 API',kind:'placeholder'},
 {id:'marketReplay',name:'行情回放',status:'INTERACTIVE',apis:['/api/v1/market/sandbox/report/latest','/api/v1/market/sandbox/snapshots','/api/v1/market/sandbox/bars','/api/v1/market/sandbox/replay/latest','/api/v1/market/sandbox/quality/latest'],source:'local_console_market_stage84/*.json',task:'market_replay_sandbox',kind:'market'},
 {id:'xtBoundary',name:'xtdata 边界/启用',status:'INTERACTIVE',apis:['/api/v1/xtdata/boundary/report','/api/v1/xtdata-enable/report','/api/v1/market/xtdata/config','/api/v1/market/xtdata/import-guard'],source:'local_console_xtdata_stage85/*.json; local_console_xtdata_enable_stage86/*.json',task:'xtdata_boundary_dry_run',kind:'generic'},
 {id:'xtLive',name:'xtdata 只读行情',status:'INTERACTIVE',apis:['/api/v1/market/xtdata-live/status','/api/v1/market/xtdata-live/snapshots','/api/v1/market/xtdata-live/bars','/api/v1/market/xtdata-live/safety','/api/v1/market/xtdata-live/report'],source:'local_console_xtdata_live_stage87/*.json; sandbox fallback when unavailable',task:'xtdata_live_readonly_smoke',kind:'market'},
 {id:'artifacts',name:'artifacts 迁移',status:'INTERACTIVE',apis:['/api/v1/artifacts/migration/report','/api/v1/artifacts/registry'],source:'local_console_artifact_migration_stage87/*.json',task:'xtdata_live_readonly_smoke',kind:'generic'}
];
const app=document.getElementById('app'), menu=document.getElementById('menu'); let state={}; let xtLiveRealReadonly=false;
menu.innerHTML=MODULES.map(m=>`<a href="#${m.id}" data-id="${m.id}">${m.name}</a>`).join('');
window.addEventListener('hashchange',render); render();
function active(){return MODULES.find(m=>m.id===(location.hash||'#overview').slice(1))||MODULES[0]}
function render(){const m=active(); document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.id===m.id)); renderInteractive(m); loadModule(m);}
function tags(){return SAFETY.map(x=>`<span class="tag">${x}</span>`).join('')}
const STAGE87_COMPAT_TEXT='当前页面：仅占位 状态：后端待开发 预计后端接口 需要实现 前端功能矩阵 / Feature Matrix 模块名称 前端页面状态 后端 API 状态 数据源路径 是否可交互 是否 dry-run 是否 read-only 当前是否占位 下一步动作 INTERACTIVE STATIC_PLACEHOLDER BACKEND_MISSING API_ERROR DATA_MISSING fallback/mock_data /api/v1/xtdata-live/status';
function renderInteractive(m){if(m.id==='xtLive')return renderXtLive(); let top=m.kind==='workflow'?`<h2>QMT AI 系统运行工作台</h2><p>主链路：QMT Gateway -&gt; Data Hub -&gt; Research -&gt; TradingAgents -&gt; Strategy Engine -&gt; Risk Gate -&gt; Human Approval -&gt; Paper Trading / Shadow Trading</p><button class="primary" onclick="runWorkflowCheck()">运行系统链路检查</button>`:`<h2>${m.name}</h2>`;app.innerHTML=`${top}<p>${tags()} <span class="tag">${m.status}</span></p><p>数据来源：<span class="source">${m.source}</span></p><div class="actions"><button onclick="loadModuleById('${m.id}')">刷新</button>${m.task?`<button class="secondary" onclick="runTask('${m.id}')">运行 dry-run 任务</button>`:''}<button onclick="showReport('${m.id}')">查看报告</button></div><div id="status" class="loading">加载中...</div><div id="content"></div><details><summary>原始 JSON 折叠查看区 / 原始 JSON 折叠区</summary><pre id="raw">等待加载</pre></details>`}
window.loadModuleById=id=>loadModule(MODULES.find(m=>m.id===id));

function xtLiveQuery(extra={}){const params=new URLSearchParams(extra); if(xtLiveRealReadonly){params.set('enable_xtdata','true'); params.set('allow_import_xtdata','true'); params.set('allow_real_market_data','true'); params.set('allow_connect_miniqmt','true'); params.set('read_only','true'); params.set('allow_xttrader','false'); params.set('allow_order_submit','false'); params.set('allow_account_query','false');} return params.toString()?`?${params.toString()}`:'';}
function renderXtLive(){app.innerHTML=`<h2>xtdata 只读行情</h2><p>${tags()} <span class="tag">INTERACTIVE</span></p><div class="card"><h3>当前模式：<span id="xtLiveMode">${xtLiveRealReadonly?'Real xtdata readonly':'Sandbox'}</span></h3><label><input id="xtLiveConfirm" type="checkbox"> 我确认只启用 xtdata 只读行情，不启用 xttrader、不查询账户、不下单</label><div class="actions"><button class="primary" onclick="enableXtLiveReadonly()">启用真实 xtdata 只读行情</button><button onclick="disableXtLiveReadonly()">关闭真实 xtdata，回到 sandbox</button><button onclick="loadXtLive('status')">刷新状态</button><button onclick="loadXtLive('snapshots')">获取快照</button><button onclick="loadXtLive('bars')">获取K线</button></div><p class="muted">默认请求不附带真实启用参数；人工确认后仅在浏览器内存中启用本次页面会话。</p></div><div id="status" class="loading">等待加载...</div><div id="content"></div><details><summary>原始 JSON 折叠查看区 / 错误详情区</summary><pre id="raw">等待加载</pre></details>`;}
window.enableXtLiveReadonly=()=>{const c=document.getElementById('xtLiveConfirm'); if(!c||!c.checked){document.getElementById('status').innerHTML='<div class="error">请先勾选人工确认复选框。</div>'; return;} xtLiveRealReadonly=true; renderXtLive(); loadXtLive('status');};
window.disableXtLiveReadonly=()=>{xtLiveRealReadonly=false; renderXtLive(); loadXtLive('status');};
async function loadXtLive(kind='status'){const status=document.getElementById('status'), raw=document.getElementById('raw'), content=document.getElementById('content'); if(!status)return; status.textContent='加载 xtdata 只读行情中...'; const urls={status:'/api/v1/market/xtdata-live/status',snapshots:'/api/v1/market/xtdata-live/snapshots',bars:'/api/v1/market/xtdata-live/bars'}; const extra=kind==='bars'?{symbol:'510300.SH',period:'1d',limit:'20'}:{symbols:'510300.SH,510500.SH,588000.SH'}; const url=urls[kind]+xtLiveQuery(extra); try{const data=await fetchJson(url); state.xtLive={url,data}; status.textContent=`当前模式：${xtLiveRealReadonly?'Real xtdata readonly':'Sandbox'}；已请求 ${url}`; raw.textContent=JSON.stringify(data,null,2); content.innerHTML=xtLiveView(data);}catch(e){status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`; raw.textContent=JSON.stringify({status:'API_ERROR',error:e.message},null,2);}}
function xtLiveView(d){const obj=d.status||d.snapshots||d.bars||d.report||d; const fields=['real_market_data','sandbox_fallback','xtdata_imported','mini_qmt_connected','no_xttrader','no_order_submitted','no_account_query']; const errors=['import_error','connection_error','get_full_tick_error','get_market_data_ex_error','error_message']; return `<div class="grid"><div class="card"><h3>状态卡片</h3>${fields.map(k=>`<p><b>${k}</b> ${escapeHtml(String(obj[k]??''))}</p>`).join('')}</div><div class="card"><h3>错误详情区</h3>${errors.map(k=>`<p><b>${k}</b> ${escapeHtml(String(obj[k]??''))}</p>`).join('')}</div><div class="card"><h3>行情数据</h3>${tableFromData(obj.snapshots||obj.bars||[])}</div></div>`;}

async function fetchJson(url){const r=await fetch(url); if(r.status===404)return {ok:false,status:'BACKEND_MISSING',next_action:`后端待开发，需要新增 ${url} API`,read_only:true,dry_run:true,no_order_submitted:true}; const j=await r.json(); if(!r.ok||j.ok===false) throw new Error(url+': '+(j.error||r.status)); return j;}
async function loadModule(m){if(m&&m.id==='xtLive')return loadXtLive('status'); if(!m||!m.apis.length)return; const status=document.getElementById('status'), raw=document.getElementById('raw'), content=document.getElementById('content'); status.textContent='加载中...'; content.innerHTML=''; try{const entries=await Promise.all(m.apis.map(async url=>[url,await fetchJson(url)])); const data=Object.fromEntries(entries); state[m.id]=data; status.textContent='已加载 '+entries.length+' 个相对路径 API；Network 可见 '+m.apis.join(', '); raw.textContent=JSON.stringify(data,null,2); content.innerHTML=view(m,data);}catch(e){status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`; raw.textContent=JSON.stringify({status:'API_ERROR',error:e.message},null,2);}}
async function postTask(task_id){let r=await fetch('/api/v1/tasks/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id,params:{limit:5,read_only:true,dry_run:true,no_order_submitted:true}})}); let j=await r.json(); if(!r.ok||j.ok===false) throw new Error(j.error||r.status); return j;}
async function runTask(id){const m=MODULES.find(x=>x.id===id); const status=document.getElementById('status'); status.textContent='dry-run 任务运行中...'; try{await postTask(m.task); await loadModule(m);}catch(e){if(m.fallbackTask){try{await postTask(m.fallbackTask); await loadModule(m); return;}catch(e2){e=e2}} status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`;}}
async function runWorkflowCheck(){const status=document.getElementById('status'); status.textContent='系统链路 dry-run 顺序检查中...'; const out=[]; for(const step of FLOW_APIS){try{if(step.startsWith('POST ')){out.push([step,await postTask(step.replace('POST ',''))]);}else{out.push([step,await fetchJson(step)]);}}catch(e){out.push([step,{status:'BACKEND_MISSING',error:e.message,next_action:`后端待开发，需要新增 ${step} API`}]);}} await postTask('workflow_dry_run_check'); state.workflowRun=Object.fromEntries(out); document.getElementById('raw').textContent=JSON.stringify(state.workflowRun,null,2); document.getElementById('content').innerHTML=workflowRunTable(state.workflowRun); status.textContent='系统链路检查完成：dry-run only，未下单。';}
function showReport(id){const raw=document.getElementById('raw'); raw.scrollIntoView({behavior:'smooth'});}
function view(m,d){if(m.kind==='workflow')return workflowView(d); if(m.kind==='featureMatrix')return featureMatrixView(d); if(m.kind==='factor')return factorView(d); return cards('接口数据 / 安全状态 / 下一步建议',d)}
function workflowView(d){const wf=d['/api/v1/workflow/status']?.workflow||[]; return `<div class="grid">${wf.map(x=>`<div class="card"><h3>${x.module||x.layer}</h3><p><b>当前状态</b> <span class="tag">${x.status}</span></p><p><b>后端 API 状态</b> ${x.api_status}</p><p><b>数据源路径</b> <span class="source">${x.data_source_path||x.data_source}</span></p><p><b>最近运行时间</b> ${x.last_run_time||'DATA_MISSING'}</p><p><b>是否可交互</b> ${x.interactive?'是':'否'}；<b>是否后端待开发</b> ${x.backend_missing?'是 BACKEND_MISSING':'否'}</p><p><b>安全边界</b> ${x.safety_boundary}</p><button onclick="runTask('${active().id}')">运行按钮</button> <button onclick="loadModuleById('${active().id}')">刷新按钮</button> <button onclick="showReport('${active().id}')">查看报告按钮</button><p><b>下一步建议</b> ${x.next_action}</p></div>`).join('')}</div>`}
function workflowRunTable(obj){return `<h3>一键顺序检查结果</h3><table><thead><tr><th>步骤</th><th>状态</th><th>下一步建议</th></tr></thead><tbody>${Object.entries(obj).map(([k,v])=>`<tr><td>${k}</td><td>${v.status||v.task?.status||'READY'}</td><td>${v.next_action||v.task?.message||'继续下一层 dry-run'}</td></tr>`).join('')}</tbody></table>`}
function featureMatrixView(d){const rows=d['/api/v1/workflow/feature-matrix']?.features||[]; return `<table class="matrix"><thead><tr><th>功能</th><th>状态</th><th>API</th><th>说明</th><th>read_only</th><th>no_order_submitted</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.feature}</td><td><span class="tag ${r.status.includes('DISABLED')?'warn':''}">${r.status}</span></td><td>${r.api||'BACKEND_MISSING'}</td><td>${r.note}</td><td>${r.read_only}</td><td>${r.no_order_submitted}</td></tr>`).join('')}</tbody></table>`}
function cards(title,d){return `<div class="grid"><div class="card"><h3>${title}</h3>${tableFromData(d)}</div><div class="card"><h3>安全状态</h3>${tags()}<p class="muted">BACKEND_MISSING / DISABLED_FOR_SAFETY 会在原始 JSON 中明确显示。</p></div></div>`}
function factorView(d){const c=(d['/api/v1/factor/candidates/latest']?.candidates||d['/api/v1/factors/candidates']?.candidates||[]);return `<div class="card"><h3>factor values / composite_score / risk_flags / ranking</h3>${candidateTable(c)}</div><div class="grid"><div class="card"><h3>因子配置面板</h3>${tableFromData(d['/api/v1/factors/config']||{})}</div><div class="card"><h3>因子报告</h3>${tableFromData(d['/api/v1/factor/report/latest']||{})}</div></div>`}
function candidateTable(rows){if(!Array.isArray(rows)||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING，暂无候选池；可点击 dry-run 生成或查看原始 JSON。</p>';const sorted=[...rows].sort((a,b)=>(b.composite_score||b.score||0)-(a.composite_score||a.score||0));return `<table><thead><tr><th>ranking</th><th>symbol/factor</th><th>factor values</th><th>composite_score</th><th>risk_flags</th><th>fallback/mock_data</th></tr></thead><tbody>${sorted.map((r,i)=>`<tr><td>${i+1}</td><td>${r.symbol||r.factor_id||r.name||''}</td><td><pre>${escapeHtml(JSON.stringify(r.factor_values||r.values||r,null,2))}</pre></td><td>${r.composite_score??r.score??''}</td><td class="risk">${(r.risk_flags||[]).join(', ')}</td><td>${r.fallback_used||r.mock_data?'是':'否'}</td></tr>`).join('')}</tbody></table>`}
function tableFromData(data){const obj=unwrap(data); if(Array.isArray(obj))return arrTable(obj); if(obj&&typeof obj==='object')return arrTable(Object.entries(obj).map(([key,value])=>({key,value:typeof value==='object'?JSON.stringify(value):value}))); return `<pre>${escapeHtml(JSON.stringify(data,null,2))}</pre>`}
function unwrap(x){if(!x||typeof x!=='object')return x; for(const k of ['features','workflow','alerts','snapshots','bars','symbols','tasks','reports','performance','attribution','agent_comparison','report','status','registry','decisions','signals','trade_intents']) if(x[k]!==undefined) return x[k]; return x}
function arrTable(rows){if(!rows||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING 或当前输出为空。</p>'; const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))].slice(0,8); return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${escapeHtml(typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??''))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
