const SAFETY=['read_only=true','dry_run=true','not_live_trading=true','no_xttrader=true','no_order_submitted=true','no_account_query=true'];
const MODULES=[
 {id:'overview',name:'总览',status:'INTERACTIVE',apis:['/api/v1/health','/api/v1/console/summary','/api/v1/tasks/catalog'],source:'console api runtime',task:null,kind:'generic'},
 {id:'marketdata',name:'行情数据',status:'INTERACTIVE',apis:['/api/v1/market/snapshot','/api/v1/market/sandbox/symbols'],source:'local readonly/mock + local_console_market_stage84',task:'market_snapshot_readonly',kind:'generic'},
 {id:'factor',name:'因子研究',status:'INTERACTIVE',apis:['/api/v1/factor/context','/api/v1/factor/candidates/latest','/api/v1/factor/report/latest','/api/v1/factors/catalog','/api/v1/factors/config'],source:'local_console_factor_stage79/factor_candidates.json; local_console_factor_stage79/factor_report.json; task-store fallback',task:'factor_research_dry_run',fallbackTask:'factor_scan',kind:'factor'},
 {id:'selection',name:'选股中心',status:'INTERACTIVE',apis:['/api/v1/strategy/factor-signals','/api/v1/strategy/trade-intents','/api/v1/strategy/risk-decisions','/api/v1/strategy/report'],source:'factor strategy dry-run task output',task:'factor_strategy_dry_run',kind:'generic'},
 {id:'strategy',name:'策略任务',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks'],source:'console task registry/store',task:'daily_pipeline_dry_run',kind:'generic'},
 {id:'agents',name:'Agent 投研',status:'INTERACTIVE',apis:['/api/v1/agents/context','/api/v1/agents/model-usage','/api/v1/agents/runs/latest','/api/v1/agents/debate/latest','/api/v1/agents/risk-review/latest','/api/v1/agents/portfolio-review/latest','/api/v1/agents/report/latest'],source:'local_console_agent_stage81/*.json',task:'agent_research_dry_run',kind:'generic'},
 {id:'ai',name:'AI 模型配置',status:'INTERACTIVE',apis:['/api/v1/ai/models/latest','/api/v1/ai/benchmark/latest','/api/v1/ai/model-usage/draft'],source:'AI provider discovery/stress-test draft cache',task:'ai_model_discovery',kind:'generic'},
 {id:'backtest',name:'回测分析',status:'INTERACTIVE',apis:['/api/v1/backtest/report/latest','/api/v1/backtest/performance/latest','/api/v1/backtest/attribution/latest','/api/v1/backtest/agent-comparison/latest','/api/v1/backtest/shadow-replay/latest'],source:'local_console_backtest_stage82/*.json',task:'backtest_dashboard_dry_run',kind:'backtest'},
 {id:'risk',name:'风控中心',status:'INTERACTIVE',apis:['/api/v1/monitoring/alerts/latest','/api/v1/monitoring/system-health/latest','/api/v1/monitoring/circuit-breaker/latest','/api/v1/monitoring/risk-events/latest'],source:'local_console_monitoring_stage83/*.json',task:'monitoring_alert_dry_run',kind:'monitoring'},
 {id:'reports',name:'报告中心',status:'INTERACTIVE',apis:['/api/v1/reports','/api/v1/backtest/report/latest','/api/v1/monitoring/report/latest'],source:'whitelisted report summaries + stage reports',task:'generate_daily_report',kind:'generic'},
 {id:'tasks',name:'任务中心',status:'INTERACTIVE',apis:['/api/v1/tasks/catalog','/api/v1/tasks'],source:'console task registry/store',task:'list_latest_reports',kind:'generic'},
 {id:'settings',name:'系统设置',status:'STATIC_PLACEHOLDER',apis:[],expected:'/api/v1/settings',source:'not implemented',need:'实现只读设置查询、运行环境检查和配置审计 API',kind:'placeholder'},
 {id:'marketReplay',name:'行情回放',status:'INTERACTIVE',apis:['/api/v1/market/sandbox/report/latest','/api/v1/market/sandbox/snapshots','/api/v1/market/sandbox/bars','/api/v1/market/sandbox/replay/latest','/api/v1/market/sandbox/quality/latest'],source:'local_console_market_stage84/*.json',task:'market_replay_sandbox',kind:'market'},
 {id:'xtBoundary',name:'xtdata 边界/启用',status:'INTERACTIVE',apis:['/api/v1/xtdata/boundary/report','/api/v1/xtdata-enable/report','/api/v1/market/xtdata/config','/api/v1/market/xtdata/import-guard','/api/v1/market/xtdata-enable/checklist','/api/v1/market/xtdata-enable/decision'],source:'local_console_xtdata_stage85/*.json; local_console_xtdata_enable_stage86/*.json',task:'xtdata_boundary_dry_run',kind:'generic'},
 {id:'xtLive',name:'xtdata 只读行情',status:'INTERACTIVE',apis:['/api/v1/xtdata-live/status','/api/v1/xtdata-live/snapshots','/api/v1/market/xtdata-live/bars','/api/v1/market/xtdata-live/safety','/api/v1/market/xtdata-live/report'],source:'local_console_xtdata_live_stage87/*.json; sandbox fallback when unavailable',task:'xtdata_live_readonly_smoke',kind:'market'},
 {id:'artifacts',name:'artifacts 迁移',status:'INTERACTIVE',apis:['/api/v1/artifacts/migration/report','/api/v1/artifacts/registry'],source:'local_console_artifact_migration_stage87/*.json',task:'xtdata_live_readonly_smoke',kind:'generic'},
 {id:'matrix',name:'前端功能矩阵 / Feature Matrix',status:'INTERACTIVE',apis:[],source:'local_console_app_stage87 MODULES metadata',task:null,kind:'matrix'}
];
const app=document.getElementById('app'), menu=document.getElementById('menu'); let state={};
menu.innerHTML=MODULES.map(m=>`<a href="#${m.id}" data-id="${m.id}">${m.name}</a>`).join('');
window.addEventListener('hashchange',render); render();
function active(){return MODULES.find(m=>m.id===(location.hash||'#overview').slice(1))||MODULES[0]}
function render(){const m=active(); document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.id===m.id)); if(m.kind==='matrix') return renderMatrix(); if(m.kind==='placeholder') return renderPlaceholder(m); renderInteractive(m); loadModule(m);}
function tags(){return SAFETY.map(x=>`<span class="tag">${x}</span>`).join('')}
function renderInteractive(m){app.innerHTML=`<h2>${m.name}</h2><p>${tags()} <span class="tag">${m.status}</span></p><p>数据来源：<span class="source">${m.source}</span></p><div class="actions"><button onclick="loadModuleById('${m.id}')">刷新</button>${m.task?`<button class="secondary" onclick="runTask('${m.id}')">运行 dry-run 任务</button>`:''}</div><div id="status" class="loading">加载中...</div><div id="content"></div><details><summary>原始 JSON 折叠查看区</summary><pre id="raw">等待加载</pre></details>`}
function renderPlaceholder(m){app.innerHTML=`<h2>${m.name}</h2><div class="card placeholder"><h3>状态：后端待开发</h3><p><b>当前页面：仅占位</b></p><p>状态枚举：<span class="tag warn">${m.status}</span> <span class="tag warn">BACKEND_MISSING</span></p><p>预计后端接口：<code>${m.expected}</code></p><p>需要实现：${m.need}</p><p>安全边界：${SAFETY.join('；')}</p></div>`}
function renderMatrix(){const rows=MODULES.filter(m=>m.id!=='matrix').map(m=>`<tr><td>${m.name}</td><td>${m.status}</td><td>${m.apis.length?'INTERACTIVE':'BACKEND_MISSING'}</td><td class="source">${m.source}</td><td>${m.status==='INTERACTIVE'?'是':'否'}</td><td>${m.task?'是':'否'}</td><td>是</td><td>${m.status==='STATIC_PLACEHOLDER'?'是':'否'}</td><td>${m.status==='INTERACTIVE'?'保持 API 合约并补充展示字段':'实现后端 API 后改为真实交互页面'}</td></tr>`).join('');app.innerHTML=`<h2>前端功能矩阵 / Feature Matrix</h2><table class="matrix"><thead><tr><th>模块名称</th><th>前端页面状态</th><th>后端 API 状态</th><th>数据源路径</th><th>是否可交互</th><th>是否 dry-run</th><th>是否 read-only</th><th>当前是否占位</th><th>下一步动作</th></tr></thead><tbody>${rows}</tbody></table><p>状态枚举：INTERACTIVE / STATIC_PLACEHOLDER / BACKEND_MISSING / API_ERROR / DATA_MISSING</p>`}
window.loadModuleById=id=>loadModule(MODULES.find(m=>m.id===id));
async function loadModule(m){if(!m||!m.apis.length)return; const status=document.getElementById('status'), raw=document.getElementById('raw'), content=document.getElementById('content'); status.textContent='加载中...'; content.innerHTML=''; try{const entries=await Promise.all(m.apis.map(async url=>{const r=await fetch(url); const j=await r.json(); if(!r.ok||j.ok===false) throw new Error(url+': '+(j.error||r.status)); return [url,j];})); const data=Object.fromEntries(entries); state[m.id]=data; status.textContent='已加载 '+entries.length+' 个 API；Network 可见 '+m.apis.join(', '); raw.textContent=JSON.stringify(data,null,2); content.innerHTML=view(m,data);}catch(e){status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`; raw.textContent=JSON.stringify({error:e.message},null,2);}}
async function runTask(id){const m=MODULES.find(x=>x.id===id); const task_id=m.task; const status=document.getElementById('status'); status.textContent='dry-run 任务运行中...'; try{let r=await fetch('/api/v1/tasks/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id,params:{limit:5,read_only:true,dry_run:true}})}); let j=await r.json(); if(!r.ok||j.ok===false) throw new Error(j.error||r.status); await loadModule(m);}catch(e){if(m.fallbackTask){try{let r=await fetch('/api/v1/tasks/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:m.fallbackTask,params:{limit:5,read_only:true,dry_run:true}})});let j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||r.status);await loadModule(m);return;}catch(e2){e=e2}} status.innerHTML=`<div class="error">API_ERROR：${escapeHtml(e.message)}</div>`;}}
function view(m,d){if(m.kind==='factor')return factorView(d); if(m.kind==='backtest')return cards('performance_metrics / attribution / agent comparison',d); if(m.kind==='monitoring')return cards('alerts / circuit breaker / system health',d); if(m.kind==='market')return cards('symbols / snapshots / bars / replay events / sandbox fallback',d); return cards('接口数据',d)}
function cards(title,d){return `<div class="grid"><div class="card"><h3>${title}</h3>${tableFromData(d)}</div><div class="card"><h3>安全状态</h3>${tags()}<p class="muted">fallback/mock_data 字段会在原始 JSON 中保留显示。</p></div></div>`}
function factorView(d){const c=(d['/api/v1/factor/candidates/latest']?.candidates||d['/api/v1/factors/candidates']?.candidates||[]);return `<div class="card"><h3>factor values / composite_score / risk_flags / ranking</h3>${candidateTable(c)}</div><div class="grid"><div class="card"><h3>因子配置面板</h3>${tableFromData(d['/api/v1/factors/config']||{})}</div><div class="card"><h3>因子报告</h3>${tableFromData(d['/api/v1/factor/report/latest']||{})}</div></div>`}
function candidateTable(rows){if(!Array.isArray(rows)||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING，暂无候选池；可点击 dry-run 生成或查看原始 JSON。</p>';const sorted=[...rows].sort((a,b)=>(b.composite_score||b.score||0)-(a.composite_score||a.score||0));return `<table><thead><tr><th>ranking</th><th>symbol/factor</th><th>factor values</th><th>composite_score</th><th>risk_flags</th><th>fallback/mock_data</th></tr></thead><tbody>${sorted.map((r,i)=>`<tr><td>${i+1}</td><td>${r.symbol||r.factor_id||r.name||''}</td><td><pre>${escapeHtml(JSON.stringify(r.factor_values||r.values||r,null,2))}</pre></td><td>${r.composite_score??r.score??''}</td><td class="risk">${(r.risk_flags||[]).join(', ')}</td><td>${r.fallback_used||r.mock_data?'是':'否'}</td></tr>`).join('')}</tbody></table>`}
function tableFromData(data){const obj=unwrap(data); if(Array.isArray(obj))return arrTable(obj); if(obj&&typeof obj==='object')return arrTable(Object.entries(obj).map(([key,value])=>({key,value:typeof value==='object'?JSON.stringify(value):value}))); return `<pre>${escapeHtml(JSON.stringify(data,null,2))}</pre>`}
function unwrap(x){if(!x||typeof x!=='object')return x; for(const k of ['alerts','snapshots','bars','symbols','tasks','reports','performance','attribution','agent_comparison','report','status','registry']) if(x[k]!==undefined) return x[k]; return x}
function arrTable(rows){if(!rows||!rows.length)return '<p class="muted">空数据提示：DATA_MISSING 或当前输出为空。</p>'; const cols=[...new Set(rows.flatMap(r=>Object.keys(r)))].slice(0,8); return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td class="${String(r[c]).includes('risk')?'risk':''}">${escapeHtml(typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??''))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
