from __future__ import annotations
from .dashboard_models import *
DASHBOARD_ROUTES=['/dashboard/overview','/dashboard/stage-status','/dashboard/latest-validation','/dashboard/warnings','/dashboard/blocking-reasons','/dashboard/manifest','/dashboard/scheduler-preview','/dashboard/safety-boundary','/dashboard/api-capability','/dashboard/detail-filter','/dashboard/next']
def _metric(n,v,st=LocalConsoleDashboardStatus.PASS,sev=LocalConsoleDashboardSeverity.INFO,s=''): return DashboardCardMetric(n,v,st,sev,s)
def _card(cls,cid,title,typ,status=LocalConsoleDashboardStatus.PASS,severity=LocalConsoleDashboardSeverity.INFO,**kw): return cls(card_id=cid,title=title,card_type=typ,status=status,severity=severity,read_only=True,dry_run_only=True,no_trade_authorization=True,**kw)
def build_stage_status_card(evidence=None):
    ev=evidence or []; crit=sum(e.critical_count for e in ev); warn=sum(e.warning_count+len(e.warnings) for e in ev); block=sum(e.blocking_reason_count+len(e.blocking_reasons) for e in ev)
    return _card(StageStatusCard,'stage-status','Stage Status Card',LocalConsoleDashboardCardType.STAGE_STATUS,metrics=[_metric('current_stage','Stage64'),_metric('latest_passed_stage','Stage63'),_metric('stage55_63_count',len([e for e in ev if e.stage in {f"Stage{i}" for i in range(55,64)}])),_metric('critical_count',crit),_metric('warning_count',warn),_metric('blocking_reason_count',block)],summary='Stage55-63 总览与 Stage64 状态卡片',metadata={'stage_status_table':[{ 'stage':e.stage,'status':e.status.value,'decision':e.decision,'critical_count':e.critical_count} for e in ev]})
def build_latest_validation_card(detail=None):
    d=detail or {}; warns=list(d.get('warnings',[]));
    status=LocalConsoleDashboardStatus.PASS if d.get('status')=='PASS' else LocalConsoleDashboardStatus.UNAVAILABLE
    if d.get('contains_nul'): warns.append('validation summary contains NUL after cleaning')
    return _card(LatestValidationCard,'latest-validation','Latest Validation Card',LocalConsoleDashboardCardType.LATEST_VALIDATION,status=status,severity=LocalConsoleDashboardSeverity.WARN if warns else LocalConsoleDashboardSeverity.INFO,metrics=[_metric('latest_validation_log_path',d.get('path','')),_metric('validation_status',d.get('status','UNKNOWN')),_metric('encoding_used',d.get('encoding','')),_metric('contains_nul',bool(d.get('contains_nul',False))),_metric('contains_replacement_char',bool(d.get('contains_replacement_char',False)))],warnings=warns,summary=str(d.get('summary','')))
def build_warning_blocking_stats_card(evidence=None):
    ev=evidence or []; wc=sum(e.warning_count+len(e.warnings) for e in ev); bc=sum(e.blocking_reason_count+len(e.blocking_reasons) for e in ev); cc=sum(e.critical_count for e in ev)
    by_stage={e.stage:{'warnings':e.warning_count+len(e.warnings),'blocking_reasons':e.blocking_reason_count+len(e.blocking_reasons),'critical':e.critical_count} for e in ev}
    return _card(WarningBlockingStatsCard,'warning-blocking-stats','Warning / Blocking Stats Card',LocalConsoleDashboardCardType.WARNING_BLOCKING_STATS,metrics=[_metric('warning_count',wc),_metric('blocking_reason_count',bc),_metric('critical_count',cc)],summary='warning/blocking reason 统计卡片',metadata={'by_stage':by_stage,'by_severity':{'WARN':wc,'CRITICAL':cc+bc}})
def build_manifest_hash_card(evidence=None):
    ev=evidence or []; missing=[e.stage for e in ev if e.status==LocalConsoleDashboardStatus.UNAVAILABLE]
    return _card(ManifestHashCard,'manifest-hash','Manifest / Hash Card',LocalConsoleDashboardCardType.MANIFEST_HASH,status=LocalConsoleDashboardStatus.WARN if missing else LocalConsoleDashboardStatus.PASS,metrics=[_metric('manifest_item_count',len(ev)),_metric('sha256_completeness','available when upstream manifest includes sha256'),_metric('missing_required_manifest_items',missing),_metric('read_only',True)],warnings=[f'missing required manifest items: {missing}'] if missing else [],summary='manifest/hash 状态卡片')
def build_scheduler_preview_card(): return _card(SchedulerPreviewCard,'scheduler-preview','Scheduler Preview Card',LocalConsoleDashboardCardType.SCHEDULER_PREVIEW,metrics=[_metric('register_preview_only',True),_metric('no_task_registered',True),_metric('dry_run_only',True),_metric('no_trade_authorization',True)],summary='register preview only; no Windows task registered')
def build_safety_boundary_card(): return _card(SafetyBoundaryCard,'safety-boundary','Safety Boundary Card',LocalConsoleDashboardCardType.SAFETY_BOUNDARY,metrics=[_metric('read_only',True),_metric('dry_run_only',True),_metric('no_trade_authorization',True),_metric('no_xttrader',True),_metric('no_account_query',True),_metric('no_order',True),_metric('no_real_notification',True)],summary='Stage64 只读安全边界')
def build_api_capability_card(api_evidence=None):
    data=(api_evidence.metadata.get('data',{}) if api_evidence else {}) or {}; routes=data.get('route_index') or data.get('routes') or []
    return _card(ApiCapabilityCard,'api-capability','API Capability Card',LocalConsoleDashboardCardType.API_CAPABILITY,metrics=[_metric('stage61_api_gateway_route_count',len(routes)),_metric('forbidden_route_count',0),_metric('read_only_routes_present',True),_metric('forbidden_routes_blocked',True)],summary='Stage61 API Gateway capability status')
def build_detail_filter_card(detail_evidence=None):
    data=(detail_evidence.metadata.get('data',{}) if detail_evidence else {}) or {}; routes=data.get('route_index') or [] ; fidx=data.get('filter_index') or {}
    return _card(DetailFilterCard,'detail-filter','Detail / Filter Card',LocalConsoleDashboardCardType.DETAIL_FILTER,metrics=[_metric('stage63_detail_route_count',len(routes)),_metric('filter_categories',list(fidx.keys())),_metric('warnings_filter_exists','warnings' in str(fidx).lower()),_metric('blocking_reasons_filter_exists','blocking' in str(fidx).lower())],summary='Stage63 detail/filter status')
def build_dashboard_card_index(cards=None): return cards or [build_stage_status_card(),build_latest_validation_card(),build_warning_blocking_stats_card(),build_manifest_hash_card(),build_scheduler_preview_card(),build_safety_boundary_card(),build_api_capability_card(),build_detail_filter_card()]
