from __future__ import annotations
from .drilldown_models import *
from .drilldown_safety import ALLOWED_HASH_ROUTES, FORBIDDEN_HASH_ROUTES, scan_drilldown_assets_for_forbidden_markers
from .drilldown_export import build_export_manifest as _build_export_manifest, build_export_snapshot as _build_export_snapshot
SAFE='本地只读控制台｜不是实盘授权｜不下单｜不调用 xttrader｜不查询真实账户｜不发送真实通知｜导出仅为本地 Markdown/JSON 复核快照'
ROUTES=[(r,r.replace('#/','').replace('-',' ').title()) for r in ALLOWED_HASH_ROUTES]

def build_drilldown_manifest(): return {'stage':'Stage70','assets':['index.html','app.js','style.css'],'routes':ALLOWED_HASH_ROUTES,'read_only':True,'safety_banner':SAFE}
def build_report_detail_index(): return [ReportDetailItem('stage69-grouping','Stage69 Grouping Evidence','local_console_grouping_report.md','PASS','INFO','Stage69','状态分组与筛选体验层证据'), ReportDetailItem('stage70-overview','Stage70 Drilldown Export','local_console_drilldown_report.md','PASS','INFO','Stage70','报告详情钻取与导出层')]
def build_drilldown_route_map(): return [ReportDrilldownRoute(r,t,True,False) for r,t in ROUTES]
def build_export_manifest(): return _build_export_manifest()
def build_export_snapshot(): return _build_export_snapshot()
def build_export_safety_report(assets=None):
    f=scan_drilldown_assets_for_forbidden_markers(assets or {}, generated=True)
    return ExportSafetyReport(f, sum(1 for x in f if x.severity==LocalConsoleDrilldownSeverity.CRITICAL), [f'{x.severity.value} marker {x.marker} in {x.path}' for x in f if x.severity!=LocalConsoleDrilldownSeverity.CRITICAL])

def build_drilldown_index_html():
    nav=''.join(f'<a class="nav-tab" href="{r}">{t}</a>' for r,t in ROUTES)
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Stage70 Local Console Drilldown</title><link rel="stylesheet" href="./style.css"></head><body><header><h1>QMT AI Trading 本地只读控制台</h1><p>Header / Project Title - Stage70 报告详情钻取与导出层</p></header><aside id="safety-banner" class="safety-banner">Safety Banner：{SAFE}</aside><nav aria-label="Navigation Tabs">{nav}</nav><main id="app"><section id="report-detail-panel"><h2>Report Detail Panel</h2><div id="report-detail-content"></div></section><section id="report-preview-panel"><h2>Report Preview Panel</h2><div id="report-preview-content"></div></section><section id="report-metadata-panel"><h2>Report Metadata Panel</h2><div id="report-metadata-content"></div></section><section id="copy-export-panel"><button id="copySummaryButton" type="button">Copy Summary Button</button><button id="exportMarkdownSnapshotButton" type="button">Export Markdown Snapshot Button</button><button id="exportJsonSnapshotButton" type="button">Export JSON Snapshot Button</button></section><section id="error-report-locator-panel"><h2>Error Report Locator Panel</h2><button id="locateErrorReportButton" type="button">Locate Error Report Button</button><div id="error-report-location"></div></section><section id="manual-review-package-entry-panel"><h2>Manual Review Package Entry Panel</h2><button id="openReviewPackageButton" type="button">Open Review Package Button</button><div id="manual-review-package-entry"></div></section><section id="loading-state">Loading State</section><section id="error-state">Error State</section><section id="empty-state">Empty State</section></main><footer>Footer：READY_FOR_LOCAL_CONSOLE_DRILLDOWN_REVIEW 只表示材料可供人工复核，不是实盘授权；不提供交易、账户、审批、通知功能。</footer><script src="./app.js"></script></body></html>'''

def build_drilldown_app_js():
    return r"""
const READ_ONLY = true;
const ALLOWED_SOURCES = ['./data_bundle.json','./binding_manifest.json','./data_source_map.json','./static_data_safety.json','./report_detail_index.json','./export_manifest.json'];
const ROUTES = ['#/dashboard','#/reports','#/reports/detail','#/reports/preview','#/reports/export','#/filters','#/warnings','#/blocking-reasons','#/manifest','#/validation','#/scheduler','#/safety','#/api','#/review-package','#/next'];
const FORBIDDEN_ROUTES = ['#/order','#/orders','#/trade','#/execute','#/approve','#/live','#/notify','#/account','#/positions','#/assets'];
let dataBundle = {}; let reportDetailIndex = []; let selectedReportId = 'stage70-overview';
function updateLastLoadedAt(){ let n=document.getElementById('last-loaded-at'); if(!n){ n=document.createElement('time'); n.id='last-loaded-at'; document.body.appendChild(n); } n.textContent=new Date().toISOString(); }
async function loadDataBundle(){ const results={}; document.getElementById('loading-state').hidden=false; for(const source of ALLOWED_SOURCES){ try{ results[source]=await fetch(source).then(r=>r.json()); }catch(error){ results[source]={read_only:READ_ONLY, warning:String(error)}; } } dataBundle=results; updateLastLoadedAt(); document.getElementById('loading-state').hidden=true; return results; }
async function loadReportDetailIndex(){ if(!dataBundle['./report_detail_index.json']) await loadDataBundle(); const raw=dataBundle['./report_detail_index.json']; reportDetailIndex = Array.isArray(raw.items) ? raw.items : (Array.isArray(raw) ? raw : []); if(!reportDetailIndex.length){ reportDetailIndex=[{report_id:'stage70-overview',title:'Stage70 Overview',summary:'本地只读控制台报告详情钻取与导出层',stage:'Stage70',status:'PASS',severity:'INFO'}]; } return reportDetailIndex; }
function findReport(reportId){ return reportDetailIndex.find(r=>r.report_id===reportId) || reportDetailIndex[0]; }
function openReportDetail(reportId){ selectedReportId=reportId || selectedReportId; const r=findReport(selectedReportId); const n=document.getElementById('report-detail-content'); if(n)n.textContent=`${r.title}: ${r.summary}`; renderReportPreview(selectedReportId); renderReportMetadata(selectedReportId); }
function renderReportPreview(reportId){ const r=findReport(reportId); const n=document.getElementById('report-preview-content'); if(n)n.textContent=`单报告预览：${r.title} / ${r.summary}。只读预览，不是实盘授权。`; }
function renderReportMetadata(reportId){ const r=findReport(reportId); const n=document.getElementById('report-metadata-content'); if(n)n.textContent=JSON.stringify({stage:r.stage,status:r.status,severity:r.severity,source_path:r.source_path,read_only:true}, null, 2); }
function copySummaryReadOnly(reportId){ const r=findReport(reportId); const text=`${r.title}: ${r.summary}`; if(navigator.clipboard){ navigator.clipboard.writeText(text).catch(()=>{}); } return {read_only:true, network_enabled:false, summary:text}; }
function exportMarkdownSnapshotReadOnly(reportId){ const r=findReport(reportId); return `# Stage70 Export Snapshot\n\n- read_only=True\n- dry_run_only=True\n- no_trade_authorization=True\n- report_id=${r.report_id}\n- summary=${r.summary}\n\n导出仅为本地 Markdown 复核快照，不是交易授权。`; }
function exportJsonSnapshotReadOnly(reportId){ const r=findReport(reportId); return {read_only:true, dry_run_only:true, no_trade_authorization:true, report_id:r.report_id, summary:r.summary, note:'导出仅为本地 JSON 复核快照，不是交易授权。'}; }
function locateErrorReportReadOnly(reportId){ const r=findReport(reportId); const n=document.getElementById('error-report-location'); const result={read_only:true, report_id:r.report_id, source_path:r.source_path || 'local_console_drilldown_report.md'}; if(n)n.textContent=JSON.stringify(result); return result; }
function renderManualReviewPackageEntry(){ const n=document.getElementById('manual-review-package-entry'); if(n)n.textContent='Stage71 人工复核工作台入口：只读 review package，不自动 approve，不下单。'; }
function renderForbiddenRouteState(){ const n=document.getElementById('error-state'); n.hidden=false; n.textContent='该路由被安全边界禁止；本地控制台不提供交易/账户/审批/通知功能。'; }
function renderCurrentRoute(){ const hash=window.location.hash || '#/dashboard'; if(hash==='#/'||hash==='#'){ window.location.hash='#/dashboard'; return; } if(FORBIDDEN_ROUTES.includes(hash) || !ROUTES.includes(hash)){ renderForbiddenRouteState(); return; } document.getElementById('error-state').hidden=true; if(!reportDetailIndex.length){ document.getElementById('empty-state').textContent='Empty State'; } openReportDetail(selectedReportId); renderManualReviewPackageEntry(); }
window.addEventListener('hashchange', renderCurrentRoute);
window.addEventListener('DOMContentLoaded',()=>{ document.getElementById('copySummaryButton').addEventListener('click',()=>copySummaryReadOnly(selectedReportId)); document.getElementById('exportMarkdownSnapshotButton').addEventListener('click',()=>exportMarkdownSnapshotReadOnly(selectedReportId)); document.getElementById('exportJsonSnapshotButton').addEventListener('click',()=>exportJsonSnapshotReadOnly(selectedReportId)); document.getElementById('locateErrorReportButton').addEventListener('click',()=>locateErrorReportReadOnly(selectedReportId)); document.getElementById('openReviewPackageButton').addEventListener('click',()=>{window.location.hash='#/review-package';}); loadDataBundle().then(loadReportDetailIndex).then(renderCurrentRoute); });
"""

def build_drilldown_style_css(): return """body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;margin:0;background:#f8fafc;color:#162033}header,.safety-banner,nav,main,footer{padding:16px 24px}.safety-banner{position:sticky;top:0;background:#fff3cd;border:1px solid #facc15;font-weight:700}nav{display:flex;gap:10px;flex-wrap:wrap;background:#0f172a}nav a{color:white;text-decoration:none}section{background:white;border:1px solid #dbe3ef;border-radius:12px;margin:12px 0;padding:16px}button{border:1px solid #2563eb;border-radius:8px;padding:8px;margin:4px;background:#eff6ff}footer{color:#475569;font-size:13px}\n"""
