from __future__ import annotations
from .review_models import *

SAFETY_BANNER='本地只读控制台｜不是实盘授权｜不下单｜不调用 xttrader｜不查询真实账户｜不发送真实通知｜人工复核工作台只是本地复核材料，不是审批授权'
ALLOWED_ROUTES=['#/dashboard','#/reports','#/reports/detail','#/reports/preview','#/reports/export','#/review-workbench','#/review-checklist','#/review-notes','#/review-package','#/local-confirmations','#/filters','#/warnings','#/blocking-reasons','#/manifest','#/validation','#/scheduler','#/safety','#/api','#/next']

def build_review_manifest(config=None): return ReviewManifestReport(assets=['index.html','app.js','style.css','review_manifest.json','review_checklist.json','review_notes_template.json','local_confirmation_checklist.json','review_package_index.json'], routes=ALLOWED_ROUTES)
def build_review_checklist(): return [ReviewChecklistItem('stage71-readonly','确认 Stage71 只读人工复核工作台',True,note='review checklist 只是确认清单，不是交易授权。'), ReviewChecklistItem('stage71-no-live','确认不下单、不查账户、不调用 xttrader',True,note='不得触发交易、账户、持仓、订单、成交或通知动作。')]
def build_review_notes_template(): return ReviewNotesTemplate(body='Review notes 只读模板：记录人工复核观察、证据缺口、修复建议。本模板不是审批授权，不是实盘授权，不下单，不调用 xttrader，不查询真实账户，不发送真实通知。')
def build_local_confirmation_checklist(): return [LocalConfirmationItem('confirm-not-approval','确认 review notes / checklist / local confirmations 都不是审批授权',True,'本地确认项不是交易授权。'), LocalConfirmationItem('confirm-risk-human','确认 UI 不能绕过 Risk Gate / Human Approval',True,'不得自动 approve。')]
def build_review_package_index(): return [ReviewPackageIndexItem('local_console_review_workbench_report.md','Workbench Report'), ReviewPackageIndexItem('review_manifest.md','Manual Review Manifest'), ReviewPackageIndexItem('review_checklist.md','Review Checklist'), ReviewPackageIndexItem('review_notes_template.md','Review Notes Template'), ReviewPackageIndexItem('local_confirmation_checklist.md','Local Confirmation Checklist'), ReviewPackageIndexItem('review_safety_report.md','Review Safety Report'), ReviewPackageIndexItem('next_ui_acceptance_summary_plan.md','Stage72 Plan')]
def build_review_safety_report(assets=None):
    from .review_safety import scan_review_assets_for_forbidden_markers
    findings=scan_review_assets_for_forbidden_markers(assets or {}, generated=True)
    return ReviewSafetyReport(findings, sum(1 for f in findings if f.severity==LocalConsoleReviewSeverity.CRITICAL), [f'{f.severity.value} marker {f.marker} in {f.path}' for f in findings if f.severity!=LocalConsoleReviewSeverity.CRITICAL])
def build_next_ui_acceptance_summary_plan(): return NextUiAcceptanceSummaryPlanReport()

def build_review_index_html():
    nav=''.join(f'<a class="nav-tab" href="{r}">{r}</a>' for r in ALLOWED_ROUTES)
    return f'''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Stage71 Local Console Manual Review Workbench</title><link rel="stylesheet" href="./style.css"></head><body><header><h1>QMT AI Trading 本地只读控制台</h1><p>Header / Project Title - Stage71 人工复核工作台层</p></header><aside class="safety-banner">Safety Banner：{SAFETY_BANNER}</aside><nav>{nav}</nav><main id="app"><section id="manual-review-workbench-panel"><h2>Manual Review Workbench Panel</h2></section><section id="review-checklist-panel"><h2>Review Checklist Panel</h2><button id="toggleChecklistItemButton" type="button">Toggle Local Only</button></section><section id="review-notes-template-panel"><h2>Review Notes Template Panel</h2><button id="copyReviewNotesButton" type="button">Copy Review Notes</button><button id="exportReviewNotesDraftButton" type="button">Export Review Notes Draft</button></section><section id="local-confirmation-checklist-panel"><h2>Local Confirmation Checklist Panel</h2></section><section id="review-package-index-panel"><h2>Review Package Index Panel</h2><button id="openReviewPackageButton" type="button">Open Review Package</button></section><section id="review-status-placeholder-panel"><h2>Review Status Placeholder Panel</h2></section><section id="review-conclusion-draft-panel"><h2>Review Conclusion Draft Panel</h2></section><section id="stage70-drilldown-evidence-panel"><h2>Stage70 Drilldown Evidence Panel</h2></section><section id="loading-state">Loading State</section><section id="error-state">Error State</section><section id="empty-state">Empty State</section></main><footer>Footer：READY_FOR_LOCAL_CONSOLE_REVIEW_WORKBENCH_REVIEW 只表示本地控制台人工复核工作台层材料可供人工复核，不是实盘授权。</footer><script src="./app.js"></script></body></html>'''

def build_review_app_js(): return r'''
const READ_ONLY = true;
// required API names: toggleChecklistItemLocalOnly() copyReviewNotesTemplateReadOnly() exportReviewNotesDraftReadOnly()
const ALLOWED_SOURCES = ['./review_manifest.json','./review_checklist.json','./review_notes_template.json','./local_confirmation_checklist.json','./review_package_index.json','./data_bundle.json','./static_data_safety.json'];
const ROUTES = ['#/dashboard','#/reports','#/reports/detail','#/reports/preview','#/reports/export','#/review-workbench','#/review-checklist','#/review-notes','#/review-package','#/local-confirmations','#/filters','#/warnings','#/blocking-reasons','#/manifest','#/validation','#/scheduler','#/safety','#/api','#/next'];
const FORBIDDEN_ROUTES = ['#/order','#/orders','#/trade','#/execute','#/approve','#/approval','#/auto-approve','#/live','#/notify','#/account','#/positions','#/assets'];
let bundle = {}; let localChecklistState = {};
async function loadDataBundle(){ const result={}; document.getElementById('loading-state').hidden=false; for(const source of ALLOWED_SOURCES){ try{ result[source]=await fetch(source).then(r=>r.json()); }catch(error){ result[source]={read_only:true, warning:String(error)}; } } bundle=result; updateLastLoadedAt(); document.getElementById('loading-state').hidden=true; return result; }
async function loadReviewManifest(){ if(!bundle['./review_manifest.json']) await loadDataBundle(); return bundle['./review_manifest.json']; }
async function loadReviewChecklist(){ if(!bundle['./review_checklist.json']) await loadDataBundle(); return bundle['./review_checklist.json']; }
function renderReviewWorkbench(){ document.getElementById('manual-review-workbench-panel').textContent='人工复核工作台：本地只读复核材料，不是审批授权，不下单。'; }
function renderReviewChecklist(){ const data=bundle['./review_checklist.json']||{}; document.getElementById('review-checklist-panel').append(document.createTextNode(JSON.stringify(data.items||data))); }
function renderReviewNotesTemplate(){ const data=bundle['./review_notes_template.json']||{}; document.getElementById('review-notes-template-panel').append(document.createTextNode(JSON.stringify(data.template||data))); }
function renderLocalConfirmationChecklist(){ const data=bundle['./local_confirmation_checklist.json']||{}; document.getElementById('local-confirmation-checklist-panel').textContent=JSON.stringify(data.items||data); }
function renderReviewPackageIndex(){ const data=bundle['./review_package_index.json']||{}; document.getElementById('review-package-index-panel').append(document.createTextNode(JSON.stringify(data.items||data))); }
function renderReviewStatusPlaceholder(){ document.getElementById('review-status-placeholder-panel').textContent='PENDING_REVIEW / REVIEWED / NEEDS_FIX：仅本地状态占位，不自动 approve。'; }
function renderReviewConclusionDraft(){ document.getElementById('review-conclusion-draft-panel').textContent='复核结论草稿：不是实盘授权，不是交易授权。'; }
function toggleChecklistItemLocalOnly(itemId){ localChecklistState[itemId || 'default']=!localChecklistState[itemId || 'default']; return {read_only:true, local_only:true, no_approval_write:true, state:localChecklistState}; }
function copyReviewNotesTemplateReadOnly(){ const text='Review notes template read-only draft; 不是审批授权。'; if(navigator.clipboard){ navigator.clipboard.writeText(text).catch(()=>{}); } return {read_only:true, network_enabled:false, text}; }
function exportReviewNotesDraftReadOnly(){ return {read_only:true, draft_only:true, no_approval_write:true, no_trade_authorization:true, note:'review notes draft 不是审批授权。'}; }
function renderForbiddenRouteState(){ const n=document.getElementById('error-state'); n.hidden=false; n.textContent='该路由被安全边界禁止；本地控制台不提供交易/账户/审批/通知/自动批准功能。'; }
function renderCurrentRoute(){ const hash=window.location.hash || '#/review-workbench'; if(hash==='#/'||hash==='#'){ window.location.hash='#/review-workbench'; return; } if(FORBIDDEN_ROUTES.includes(hash) || !ROUTES.includes(hash)){ renderForbiddenRouteState(); return; } document.getElementById('error-state').hidden=true; renderReviewWorkbench(); renderReviewChecklist(); renderReviewNotesTemplate(); renderLocalConfirmationChecklist(); renderReviewPackageIndex(); renderReviewStatusPlaceholder(); renderReviewConclusionDraft(); }
function updateLastLoadedAt(){ let n=document.getElementById('last-loaded-at'); if(!n){ n=document.createElement('time'); n.id='last-loaded-at'; document.body.appendChild(n); } n.textContent=new Date().toISOString(); }
window.addEventListener('hashchange', renderCurrentRoute);
window.addEventListener('DOMContentLoaded',()=>{ document.getElementById('toggleChecklistItemButton').addEventListener('click',()=>toggleChecklistItemLocalOnly('stage71-readonly')); document.getElementById('copyReviewNotesButton').addEventListener('click',copyReviewNotesTemplateReadOnly); document.getElementById('exportReviewNotesDraftButton').addEventListener('click',exportReviewNotesDraftReadOnly); document.getElementById('openReviewPackageButton').addEventListener('click',()=>{window.location.hash='#/review-package';}); loadDataBundle().then(loadReviewManifest).then(loadReviewChecklist).then(renderCurrentRoute); });
'''
def build_review_style_css(): return 'body{font-family:system-ui;margin:0;background:#f8fafc;color:#172033}header,.safety-banner,nav,main,footer{padding:16px 24px}.safety-banner{background:#fff3cd;border:1px solid #facc15;font-weight:700}.nav-tab{margin:4px;display:inline-block}section{background:white;border:1px solid #dbe3ef;border-radius:12px;margin:12px 0;padding:16px}button{border:1px solid #2563eb;border-radius:8px;padding:8px;margin:4px;background:#eff6ff}'
