from __future__ import annotations
import argparse, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from qmt_ai_trading.local_console.dashboard_models import LocalConsoleDashboardDecision
from qmt_ai_trading.local_console.dashboard_service import *
def main(argv=None):
    p=argparse.ArgumentParser()
    p.add_argument('--repo-root',default='.' ); p.add_argument('--output-dir',default='local_console_dashboard_stage64')
    for n,d in [('local-console-detail-dir','local_console_detail_stage63'),('local-console-dir','local_console_stage62'),('api-gateway-dir','api_gateway_stage61'),('pre-gray-final-review-dir','pre_gray_final_review_stage60'),('readonly-seal-dir','live_gray_readonly_seal_stage59'),('final-approval-dir','live_gray_final_approval_stage58'),('gray-candidate-dir','live_gray_candidate_stage57'),('real-cache-quality-dir','real_cache_quality_stage56'),('qmt-dryrun-calibration-dir','qmt_dryrun_calibration_stage55')]: p.add_argument('--'+n,default=d)
    outs=['output','json-output','card-index-output','card-index-json-output','stage-cards-output','stage-cards-json-output','stats-output','stats-json-output','manifest-output','manifest-json-output','scheduler-output','scheduler-json-output','safety-output','safety-json-output','plan-output','plan-json-output']
    defaults=['local_console_dashboard_stage64/local_console_dashboard_report.md','local_console_dashboard_stage64/local_console_dashboard_report.json','local_console_dashboard_stage64/dashboard_card_index.md','local_console_dashboard_stage64/dashboard_card_index.json','local_console_dashboard_stage64/stage_status_cards.md','local_console_dashboard_stage64/stage_status_cards.json','local_console_dashboard_stage64/warning_blocking_stats.md','local_console_dashboard_stage64/warning_blocking_stats.json','local_console_dashboard_stage64/manifest_hash_status.md','local_console_dashboard_stage64/manifest_hash_status.json','local_console_dashboard_stage64/scheduler_preview_status.md','local_console_dashboard_stage64/scheduler_preview_status.json','local_console_dashboard_stage64/safety_boundary_status.md','local_console_dashboard_stage64/safety_boundary_status.json','local_console_dashboard_stage64/next_console_shell_plan.md','local_console_dashboard_stage64/next_console_shell_plan.json']
    for a,d in zip(outs,defaults): p.add_argument('--'+a,default=d)
    a=p.parse_args(argv); cfg=build_default_local_console_dashboard_config(repo_root=a.repo_root,output_dir=a.output_dir,local_console_detail_dir=a.local_console_detail_dir,local_console_dir=a.local_console_dir,api_gateway_dir=a.api_gateway_dir,pre_gray_final_review_dir=a.pre_gray_final_review_dir,readonly_seal_dir=a.readonly_seal_dir,final_approval_dir=a.final_approval_dir,gray_candidate_dir=a.gray_candidate_dir,real_cache_quality_dir=a.real_cache_quality_dir,qmt_dryrun_calibration_dir=a.qmt_dryrun_calibration_dir)
    r=run_local_console_dashboard_review(cfg)
    save_local_console_dashboard_report(r,a.output,a.json_output); save_dashboard_card_index_report(build_dashboard_card_index_report(r),a.card_index_output,a.card_index_json_output); save_stage_status_cards_report(build_stage_status_cards_report(r),a.stage_cards_output,a.stage_cards_json_output); save_warning_blocking_stats_report(build_warning_blocking_stats_report(r),a.stats_output,a.stats_json_output); save_manifest_hash_status_report(build_manifest_hash_status_report(r),a.manifest_output,a.manifest_json_output); save_scheduler_preview_status_report(build_scheduler_preview_status_report(r),a.scheduler_output,a.scheduler_json_output); save_safety_boundary_status_report(build_safety_boundary_status_report(r),a.safety_output,a.safety_json_output); save_next_console_shell_plan_report(build_next_console_shell_plan_report(cfg),a.plan_output,a.plan_json_output)
    print(f'Stage64 local console dashboard review package written: {a.output} decision={r.decision.value} read_only=True dry_run_only=True no_trade_authorization=True no_task_registered=True')
    return 1 if r.decision==LocalConsoleDashboardDecision.NO_GO else 0
if __name__=='__main__': raise SystemExit(main())
