from __future__ import annotations

def default_final_authorization_checklist_items():
    return ["Confirm this package is review-only.","Confirm live trading remains disabled.","Confirm no live order will be submitted by this package.","Confirm Live Env Check evidence is present and reviewed.","Confirm Live Manual Prep evidence is present and reviewed.","Confirm Gray Decision Package evidence is present and reviewed.","Confirm Gray Rehearsal evidence is present and reviewed.","Confirm Risk Gate evidence is present and no bypass exists.","Confirm Human Approval evidence is present and explicit.","Confirm Paper Trading evidence is dry-run/local only.","Confirm Live Readiness Audit has no critical failures.","Confirm Monitoring has no CRITICAL alerts and Circuit Breaker is not OPEN.","Confirm Data Quality Tracking is acceptable for manual review.","Confirm Agent Research is read-only.","Confirm Live Gray Readiness does not auto-GO.","Confirm Notification Dry Run did not send real messages.","Confirm Dashboard is read-only and has no order entry.","Confirm max total capital is extremely small and explicit.","Confirm max single order value is extremely small and explicit.","Confirm allowed symbols are whitelisted.","Confirm no xttrader or QMT trading API was called.","Confirm no account/fund/position/order/trade query was called.","Confirm no order was submitted.","Confirm final approver manually signs before any future separate stage."]
def default_final_forbidden_items():
    return ["No automatic live enable.","No automatic approval.","No automatic paper submit.","No automatic live submit.","No real notification send.","No xttrader.","No QMT trading API.","No account/fund/position/order/trade query.","No order submission.","No bypassing Risk Gate or Human Approval.","No hidden live flag.","No using this package as trading authorization."]
def default_final_residual_risks():
    return ["Data quality may still be incomplete.","Paper trading may differ from real execution.","Slippage and liquidity risks remain.","Operational mistakes remain possible.","QMT environment differences remain possible.","Manual approval mistakes remain possible.","Network / client / broker behavior may differ from test assumptions.","Strategy may fail in real market conditions."]
def default_future_stage_requirements():
    return ["新阶段必须单独人工确认。","新阶段仍默认关闭实盘。","必须再次确认 QMT 环境。","必须再次确认 Risk Gate。","必须再次确认 Human Approval。","必须再次确认 Paper Trading。","必须再次确认 Live Readiness Audit。","必须再次确认 Monitoring / Circuit Breaker。","必须再次确认 Notification 是否仍 dry-run。","必须再次确认 allowed_symbols 和 capital limits。","不得直接从本包自动执行交易。"]
def build_final_authorization_checklist(package): return default_final_authorization_checklist_items()
def build_final_authorization_signoff_placeholders(package):
    return ["Operator signature: ____________________","Reviewer signature: ____________________","Risk owner signature: ____________________","Final approver signature: ____________________","Date: ____________________","Final manual decision: ____________________","Explicit statement: This signature still does not submit orders."]
def format_final_authorization_checklist(package): return "\n".join(f"- [ ] {x}" for x in build_final_authorization_checklist(package))
