"""Base agent interfaces.

Agents only produce structured decisions. They must not submit orders or execute
Python code generated by an LLM. Later phases may reference the multi-agent
research workflow from TradingAgents / TradingAgents-CN, but stage one does not
integrate their source code.
"""

from __future__ import annotations

from qmt_ai_trading.common.types import AgentDecision


class BaseAgent:
    """Minimal base class for analysis-only agents."""

    name = "base_agent"

    def analyze(self, symbol: str) -> AgentDecision:
        """Return a neutral decision placeholder."""

        return AgentDecision(
            symbol=symbol,
            signal="HOLD",
            confidence=0.0,
            score=0.0,
            max_position_pct=0.0,
            reasons=["stage-1 analysis-only placeholder"],
            risk_flags=["agent output is advisory only"],
        )
